using System;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Verifiable.Cryptography;
using Verifiable.Foundation.Automata;
using Verifiable.Tpm.Spec;
using Verifiable.Tpm.Spec.Algorithms;
using Verifiable.Tpm.Spec.Structures;
using Verifiable.Tpm.Spec.Constants;
using Verifiable.Tpm.Spec.Handles;

namespace Verifiable.Tpm.Automata;

/// <summary>
/// The complete state of the TPM simulator's pushdown automaton: the lifecycle phase plus the
/// persistent characteristics and results that command admissibility and responses depend on.
/// </summary>
/// <remarks>
/// <para>
/// This is the single "fat" operational record carried by one <c>PushdownAutomaton</c> per simulated
/// TPM (one automaton, one run identifier, one trace stream). The lifecycle
/// skeleton keeps persistent and volatile data flat; the persistent/volatile partition (NV blobs,
/// sessions, transient objects) is introduced when those features are modelled.
/// </para>
/// <para>
/// <see cref="NextAction"/> carries the effectful work the runner must perform before the next input,
/// following the PDA action convention; the lifecycle commands need no effects, so it is
/// <see cref="NullAction.Instance"/> throughout this skeleton. <see cref="ResponseIntent"/> carries the
/// logical response produced by the command that was just processed.
/// </para>
/// </remarks>
/// <param name="TpmId">The stable identifier of this simulated TPM; also the automaton's run identifier.</param>
/// <param name="Phase">The current lifecycle phase.</param>
/// <param name="ConfiguredSelfTest">
/// The modelled self-test behaviour of this TPM (a fixed hardware characteristic), used to decide the
/// outcome of <c>TPM2_SelfTest()</c>.
/// </param>
/// <param name="SelfTest">The self-test outcome since the last <c>_TPM_Init</c>.</param>
/// <param name="LastOrderlyShutdown">
/// The startup type recorded by the most recent <c>TPM2_Shutdown()</c>, or <see langword="null"/> when
/// no orderly Shutdown(STATE) is pending — either none was recorded or a startup has consumed it.
/// Determines whether a subsequent <c>Startup(STATE)</c> can resume (TPM 2.0 Library Part 1, clause
/// 10.2.3.2). A disorderly power loss is not modelled in this skeleton: power-on is always the orderly
/// <c>_TPM_Init</c>, which preserves a recorded shutdown until a startup consumes it.
/// </param>
/// <param name="Clock">
/// The free-running clock in milliseconds (TPM 2.0 Library Part 1, clause 36.3): never rolled back by a startup
/// of any kind, only advanced by <see cref="ClockAdvanceQuantumMs"/> per dispatched command
/// (<c>TpmLifecycleTransitions.OnCommand</c>) or set forward by a successful <c>TPM2_ClockSet()</c>. The single
/// exception is <c>TPM2_Clear()</c>, which sets it to zero (Part 3, clause 24.6.1) — an owner change discards the
/// timeline the old owner's attestations were measured against, which is why <see cref="ClockSafe"/> is
/// simultaneously asserted.
/// </param>
/// <param name="Time">
/// The time in milliseconds since the last <c>_TPM_Init</c>/<c>TPM2_Startup()</c> (TPM 2.0 Library Part 1,
/// clause 36.2): advances with <see cref="Clock"/> on every dispatched command and is reset to zero by every
/// <c>TPM2_Startup()</c> (Reset, Restart, and Resume alike), unlike <see cref="Clock"/>.
/// </param>
/// <param name="ResetCount">
/// The count of TPM Resets since the last <c>TPM2_Clear()</c> (TPM 2.0 Library Part 1, clause 36.4):
/// incremented on every TPM Reset, reset to zero only by <c>TPM2_Clear()</c> (Part 3, clause 24.6.1).
/// </param>
/// <param name="TimeEpoch">
/// The TPM's current time epoch — the carrier for the <c>[timeEpoch]</c> term folded into a
/// <c>TPMT_TK_AUTH</c> ticket's HMAC (TPM 2.0 Library Part 2, clause 10.7.5, Table 111's equation 6) whenever
/// the ticket has a non-zero timeout. Its purpose is invalidating a time-based assertion — live or ticketed —
/// across a discontinuity in the TPM's time measurement (Part 1, clause 17.7.12); this simulator models that
/// discontinuity as every completed <c>TPM2_Startup()</c> (Reset, Restart, and Resume alike, since <see
/// cref="Time"/> resets to zero in all three here), not Reset alone. The value carries no secrecy requirement
/// of its own — the ticket HMAC's actual secrecy comes entirely from the per-hierarchy proof, never from
/// <see cref="TimeEpoch"/>, which the formula folds in cleartext — so it need only CHANGE across a
/// discontinuity, not stay hidden. It is drawn from the injected entropy seam exactly once, at construction
/// (mirroring the hierarchy-proof seed), and thereafter regenerated by deterministic bit-mixing on each
/// completed <c>TPM2_Startup()</c> rather than a fresh entropy draw — drawing fresh entropy on every Startup
/// would perturb <c>TPM2_GetRandom()</c>'s deterministic counter stream that existing byte-exact test
/// assertions rely on, for a value that does not need it.
/// </param>
/// <param name="RestartCount">
/// The count of TPM Restarts and Resumes since the last TPM Reset (TPM 2.0 Library Part 1, clause 36.5):
/// incremented on every TPM Restart or TPM Resume, reset to zero by a TPM Reset and by <c>TPM2_Clear()</c>
/// (TPM 2.0 Library Part 3, clause 24.6.1).
/// </param>
/// <param name="ClockSafe">
/// Whether the reported <see cref="Clock"/> value is guaranteed not to repeat a previously reported one
/// (TPM 2.0 Library Part 1, clause 36.3). Set to <see cref="TpmiYesNo.Yes"/> by a successful
/// <c>TPM2_ClockSet()</c> (TPM 2.0 Library Part 3, clause 29.2), by <c>TPM2_Clear()</c> alongside the
/// <see cref="Clock"/> it zeroes (clause 24.6.1's "set Safe to YES"), and by a TPM Reset that either followed an
/// orderly <c>TPM2_Shutdown(CLEAR)</c> or is this TPM's very first Reset (<see cref="ResetCount"/> was zero
/// beforehand, so no prior <see cref="Clock"/> value could ever have been reported); <see cref="TpmiYesNo.No"/>
/// after a TPM Reset with neither of those conditions — a Reset this simulator cannot distinguish from a
/// disorderly power loss following prior operation.
/// </param>
/// <param name="ClockAdvanceQuantumMs">
/// The fixed number of milliseconds <see cref="Clock"/> and <see cref="Time"/> advance for every admitted
/// command, fixed at construction (the simulator's stand-in for a real TPM's free-running Time oscillator,
/// TPM 2.0 Library Part 1, clause 36.1) and unaffected by any transition.
/// </param>
/// <param name="FailedTries">
/// The dictionary-attack failure counter (<c>failedTries</c>, reported as <c>TPM_PT_LOCKOUT_COUNTER</c>):
/// incremented on each <c>TPM_RC_AUTH_FAIL</c>, reset by <c>TPM2_DictionaryAttackLockReset()</c>
/// (TPM 2.0 Library Part 1, clause 17.8).
/// </param>
/// <param name="MaxTries">
/// The number of authorization failures tolerated before lockout engages (<c>maxTries</c>, reported as
/// <c>TPM_PT_MAX_AUTH_FAIL</c>). The TPM is in Lockout mode once <see cref="FailedTries"/> reaches this
/// value (clause 17.8.3 states <c>failedTries == maxTries</c>; see <see cref="IsInLockout"/> for the
/// defensive <c>&gt;=</c> comparison).
/// </param>
/// <param name="RecoveryTime">
/// The seconds between automatic decrements of <see cref="FailedTries"/> (<c>recoveryTime</c>, reported
/// as <c>TPM_PT_LOCKOUT_INTERVAL</c>).
/// </param>
/// <param name="LockoutRecovery">
/// The seconds to wait after a failed <c>lockoutAuth</c> use before it may be retried
/// (<c>lockoutRecovery</c>, reported as <c>TPM_PT_LOCKOUT_RECOVERY</c>).
/// </param>
/// <param name="LockoutAuth">
/// The lockout-hierarchy authorization value (TPM 2.0 Library Part 1, clause 17.8.5), checked by
/// <c>TPM2_DictionaryAttackLockReset()</c> and <c>TPM2_DictionaryAttackParameters()</c>. Empty by default,
/// mirroring <see cref="OwnerAuth"/>; <c>TPM2_HierarchyChangeAuth()</c> rotates it and <c>TPM2_Clear()</c>
/// returns it to the Empty Buffer (TPM 2.0 Library Part 1, clause 11.7).
/// </param>
/// <param name="LockoutAuthEnabled">
/// Whether <see cref="LockoutAuth"/> may currently be used, independent of <see cref="FailedTries"/> and
/// <see cref="MaxTries"/> (clause 17.8.5): a single failed <c>lockoutAuth</c> use clears this regardless of the
/// counters, and it self-heals only after <see cref="LockoutRecovery"/> seconds of elapsed <see cref="Time"/>
/// (or, when <see cref="LockoutRecovery"/> is zero, only a TPM Reset re-arms it). <see langword="true"/> for a
/// freshly powered-off TPM.
/// </param>
/// <param name="LastFailedTriesRecoveryTime">
/// The <see cref="Time"/> value the self-heal accounting for <see cref="FailedTries"/> is anchored to: reset to
/// the current <see cref="Time"/> on every counted authorization failure, and advanced by whole multiples of
/// <see cref="RecoveryTime"/> seconds as decrements are applied (clause 17.8.4).
/// </param>
/// <param name="LastLockoutAuthFailureTime">
/// The <see cref="Time"/> value at which <see cref="LockoutAuthEnabled"/> was last cleared by a failed
/// <c>lockoutAuth</c> use — the anchor <see cref="LockoutRecovery"/> seconds are measured from before it
/// self-heals back to enabled (clause 17.8.5).
/// </param>
/// <param name="NvIndexes">
/// The defined NV Indexes, keyed by handle. Populated by <c>TPM2_NV_DefineSpace()</c> and consulted by
/// <c>TPM2_NV_Read()</c>; the dictionary-attack/PIN flow drives authorization failures through a
/// DA-protected NV Index (TPM 2.0 Library Part 1, clause 17.8.1).
/// </param>
/// <param name="NvCounterHighWaterMark">
/// The phantom counter (TPM 2.0 Library Part 1, clause 37.2.6.3 NOTE 2/NOTE 6): the highest value any
/// <c>TPM_NT_COUNTER</c> Index has held at the moment it was deleted by <c>TPM2_NV_UndefineSpace()</c>. The
/// first <c>TPM2_NV_Increment()</c> of a newly (re)defined counter seeds from this value plus one, so deleting
/// and redefining the same handle can never repeat or roll back a value that Name has already reported. Zero
/// for a TPM on which no counter has ever been deleted; unaffected by any other command, including power
/// cycles, since it lives on <see cref="TpmSimulatorState"/> rather than the removed <see cref="NvIndexState"/>.
/// <c>TPM2_Clear()</c> deletes owner-created Indexes wholesale and so retires their counters into this mark by
/// the same rule, and never lowers it: an owner change is not licence to replay a counter value the departing
/// owner's Name already reported.
/// </param>
/// <param name="OwnerAuth">
/// The owner-hierarchy authorization value. Owner authorization is not dictionary-attack protected
/// (clause 17.8.1), so a wrong owner authValue is a plain bad-authorization, never a counter-feeding
/// auth-failure. Empty by default; <c>TPM2_HierarchyChangeAuth()</c> sets it and <c>TPM2_Clear()</c> returns it
/// to the Empty Buffer (TPM 2.0 Library Part 1, clause 11.4).
/// </param>
/// <param name="EndorsementAuth">
/// The endorsement-hierarchy authorization value (TPM 2.0 Library Part 1, clause 11.5). Like
/// <see cref="OwnerAuth"/> it is a permanent-entity authValue outside dictionary-attack protection
/// (clause 17.8.1), so a mismatch is a plain bad-authorization. Empty at manufacture.
/// </param>
/// <param name="PlatformAuth">
/// The platform-hierarchy authorization value (TPM 2.0 Library Part 1, clause 11.3). Platform authorizations
/// are categorically exempt from dictionary-attack gating (Part 3, clause 25.1: authorizations for entities in
/// the Platform hierarchy are never locked out), which is what makes it the recovery path when every other
/// hierarchy is locked. Empty at manufacture, and empty again after every TPM Reset and TPM Restart: "On TPM
/// Reset or TPM Restart, platformAuth is set to an EmptyAuth" (clause 11.3), which Part 3, clause 9.3 states as
/// a bullet on both startup forms, "platformAuth and platformPolicy shall be set to the Empty Buffer". Only a
/// TPM Resume carries an installed value forward. That per-boot lifetime is what separates it from
/// <see cref="OwnerAuth"/> and <see cref="LockoutAuth"/>, which persist until <c>TPM2_Clear()</c>: platform
/// firmware installs this one afresh each boot, so a value installed before a power cycle authorizes nothing
/// after it.
/// </param>
/// <param name="OwnerAuthPolicy">
/// The storage hierarchy's authorization policy digest (<c>ownerPolicy</c>, TPM 2.0 Library Part 1, clause
/// 11.4), in an owned pooled <c>TPM2B_DIGEST</c> carrier (Part 2, clause 10.4.2, Table 92) the state replaces
/// through <see cref="WithHierarchyAuthPolicy"/> and releases at <c>TPM2_Clear()</c> or teardown. Empty means
/// policy authorization of the owner hierarchy is disabled, not that every policy matches:
/// "When the authPolicy is empty, it cannot match any policyDigest value so the use of authPolicy is disabled"
/// (clause 11.2, Table 5). Empty at manufacture.
/// </param>
/// <param name="OwnerAuthPolicyHashAlg">
/// The hash algorithm <see cref="OwnerAuthPolicy"/> is expressed under, which also fixes that digest's length.
/// <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/> exactly when the policy is empty (TPM 2.0 Library Part 3,
/// clause 24.3.2: "If the authPolicy is an Empty Buffer, then this field shall be TPM_ALG_NULL").
/// </param>
/// <param name="EndorsementAuthPolicy">
/// The endorsement hierarchy's authorization policy digest (<c>endorsementPolicy</c>, TPM 2.0 Library Part 1,
/// clause 11.5), carrying the same empty-means-disabled rule as <see cref="OwnerAuthPolicy"/>. Empty at
/// manufacture.
/// </param>
/// <param name="EndorsementAuthPolicyHashAlg">
/// The hash algorithm <see cref="EndorsementAuthPolicy"/> is expressed under, on the same
/// <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/>-when-empty rule as <see cref="OwnerAuthPolicyHashAlg"/>.
/// </param>
/// <param name="PlatformAuthPolicy">
/// The platform hierarchy's authorization policy digest (<c>platformPolicy</c>, TPM 2.0 Library Part 1, clause
/// 11.3), carrying the same empty-means-disabled rule as <see cref="OwnerAuthPolicy"/>. Empty at manufacture,
/// and returned to the Empty Buffer by every TPM Reset and TPM Restart on the same bullet that empties
/// <see cref="PlatformAuth"/> beside it (Part 3, clause 9.3; clause 11.3's "platformPolicy is set to an Empty
/// Policy"), so a TPM Resume is the only startup form an installed platform policy survives. Alone among the
/// four hierarchy policies it therefore closes its own policy path at each boot rather than persisting until
/// the command that installed it is issued again.
/// </param>
/// <param name="PlatformAuthPolicyHashAlg">
/// The hash algorithm <see cref="PlatformAuthPolicy"/> is expressed under, on the same
/// <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/>-when-empty rule as <see cref="OwnerAuthPolicyHashAlg"/>, which
/// is what returns it to <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/> whenever a Reset or Restart empties that
/// digest.
/// </param>
/// <param name="LockoutAuthPolicy">
/// The lockout entity's authorization policy digest (<c>lockoutPolicy</c>, TPM 2.0 Library Part 1, clause
/// 11.7), carrying the same empty-means-disabled rule as <see cref="OwnerAuthPolicy"/>. It is the one policy
/// among the four whose satisfaction is exempted from Lockout mode for
/// <c>TPM2_DictionaryAttackLockReset()</c> (clause 17.8.5). Empty at manufacture.
/// </param>
/// <param name="LockoutAuthPolicyHashAlg">
/// The hash algorithm <see cref="LockoutAuthPolicy"/> is expressed under, on the same
/// <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/>-when-empty rule as <see cref="OwnerAuthPolicyHashAlg"/>.
/// </param>
/// <param name="PhEnable">
/// The platform hierarchy's enable (<c>phEnable</c>, <c>TPMA_STARTUP_CLEAR.phEnable</c>; TPM 2.0 Library Part
/// 1, clause 11.3). While CLEAR, neither <see cref="PlatformAuth"/> nor <see cref="PlatformAuthPolicy"/> can
/// authorize anything and no object in the platform hierarchy can be used. Its asymmetry is the strongest of
/// the four: it is SET at manufacture and re-SET by every completed <c>TPM2_Startup()</c> — Reset, Restart and
/// Resume alike, on Part 3, clause 9.3's every-startup bullet "phEnable shall be SET" — and no command can ever
/// SET it (clause 24.2.1: "phEnable may not be SET using this command"), so clearing it is one-way until a
/// startup.
/// </param>
/// <param name="ShEnable">
/// The storage hierarchy's enable (<c>shEnable</c>, <c>TPMA_STARTUP_CLEAR.shEnable</c>; TPM 2.0 Library Part 1,
/// clause 11.4). While CLEAR, neither <see cref="OwnerAuth"/> nor <see cref="OwnerAuthPolicy"/> can authorize
/// anything and NV Indexes with <c>TPMA_NV_PLATFORMCREATE</c> CLEAR are inaccessible (Part 3, clause 24.2.1).
/// SET at manufacture and re-SET by a TPM Reset and a TPM Restart alike (clause 9.3 names "phEnableNV, shEnable
/// and ehEnable shall be SET" on both), but not by a TPM Resume, which carries it forward as it was.
/// </param>
/// <param name="EhEnable">
/// The endorsement hierarchy's enable (<c>ehEnable</c>, <c>TPMA_STARTUP_CLEAR.ehEnable</c>; TPM 2.0 Library
/// Part 1, clause 11.5). While CLEAR, neither <see cref="EndorsementAuth"/> nor
/// <see cref="EndorsementAuthPolicy"/> can authorize anything and no object in the endorsement hierarchy can be
/// used. SET at manufacture and re-SET by a TPM Reset and a TPM Restart alike, but not by a TPM Resume, on the
/// same clause 9.3 bullet that governs <see cref="ShEnable"/>.
/// </param>
/// <param name="PhEnableNV">
/// The platform NV enable (<c>phEnableNV</c>, <c>TPMA_STARTUP_CLEAR.phEnableNV</c>; TPM 2.0 Library Part 1,
/// clause 11.1). It gates the NV space the platform firmware defines independently of
/// <see cref="PhEnable"/>: while CLEAR, every NV Index with <c>TPMA_NV_PLATFORMCREATE</c> SET is inaccessible
/// (Part 3, clause 24.2.1). SET at manufacture and re-SET by a TPM Reset and a TPM Restart alike, but not by a
/// TPM Resume, on the same clause 9.3 bullet that governs <see cref="ShEnable"/>.
/// </param>
/// <param name="DisableClear">
/// Whether <c>TPM2_Clear()</c> is refused (<c>TPMA_PERMANENT.disableClear</c>; TPM 2.0 Library Part 1, clause
/// 11.8.2: "If disableClear is CLEAR, then TPM2_Clear() can be authorized using either Platform Authorization
/// or Lockout Authorization. If the control is SET, then TPM2_Clear() is not functional"). Alone among the
/// controls modelled beside it this one is fixed once, at manufacture, to <see langword="false"/>: it appears
/// in none of Part 3 clause 9.3's Reset, Restart, or Resume bullet lists, so no <c>TPM2_Startup()</c> form
/// restores it and its value persists across every power cycle until <c>TPM2_ClearControl()</c> changes it.
/// </param>
/// <param name="StorageProofSeed">
/// The rotatable seed the storage and endorsement hierarchy proofs (<c>shProof</c>, <c>ehProof</c>) derive
/// from — the simulator's stand-in for the Storage Primary Seed a real TPM keeps in NV (TPM 2.0 Library Part 1,
/// clauses 12.4.4 and 12.5). It is state rather than a construction-time constant precisely because
/// <c>TPM2_Clear()</c> replaces it from the RNG (Part 3, clause 24.6.1), which is the whole mechanism by which
/// outstanding owner/endorsement tickets and saved contexts stop verifying: they are HMACs keyed by a proof
/// derived from this seed, so rotating it invalidates them structurally, with no revocation pass over any
/// list. The platform hierarchy's proof derives from a separate, construction-fixed seed and therefore
/// survives (clause 12.5: "phProof changes when the PPS changes"). At manufacture this holds the
/// <see cref="Automata.StorageProofSeed.Empty"/> sentinel and proof derivation falls back to that platform
/// seed, so a freshly manufactured TPM's per-hierarchy proofs are exactly what a single-seed derivation
/// yields; only <c>TPM2_Clear()</c> installs a generated seed here and parts them.
/// </param>
/// <param name="TransientObjects">
/// The loaded transient objects, keyed by handle. Populated by <c>TPM2_CreatePrimary()</c> and consulted by
/// <c>TPM2_Sign()</c>; the object/signing path the create-then-sign slice exercises (TPM 2.0 Library Part 3,
/// clauses 24.1 and 20.2).
/// </param>
/// <param name="PersistentObjects">
/// The persistent objects, keyed by their persistent handle (<c>TPM_HT_PERSISTENT</c>, MSO <c>0x81</c>).
/// <c>TPM2_EvictControl()</c> persists a transient object here (a copy, the transient stays loaded) and evicts
/// one from here; this is the object-persistence half of a provisioning flow (TPM 2.0 Library Part 3, clause 28.5).
/// </param>
/// <param name="LoadedSealedObjects">
/// The loaded sealed data objects, keyed by transient handle. Populated by <c>TPM2_Load()</c> of a wrapped
/// KEYEDHASH object and consulted by <c>TPM2_Unseal()</c>; the seal-then-unseal path the create/load/unseal
/// slice exercises (TPM 2.0 Library Part 3, clauses 12.1, 12.2, and 12.7).
/// </param>
/// <param name="Sha256PcrBank">
/// The SHA-256 Platform Configuration Register bank. Read by <c>TPM2_PCR_Read()</c> and hashed into the
/// composite digest <c>TPM2_Quote()</c> signs (TPM 2.0 Library Part 1, clause 17.1). Initialized to its reset
/// image at power-on; this slice models no <c>TPM2_PCR_Extend()</c>, so the registers stay at their reset value.
/// </param>
/// <param name="PcrUpdateCounter">
/// The count of PCR changes this TPM has recorded (<c>pcrUpdateCounter</c>), framed by <c>TPM2_PCR_Read()</c>
/// and captured by a <c>TPM2_PolicyPCR()</c> assertion so that session can be invalidated once the value moves
/// (TPM 2.0 Library Part 1, clause 17.1). <c>TPM2_Clear()</c> increments it for exactly that reason — "This
/// permits an application to create a policy session that is invalidated on TPM2_Clear()... The session is
/// invalidated even if the PCR selection is empty" (Part 3, clause 24.6.1). Zero for a freshly manufactured TPM.
/// </param>
/// <param name="PolicySessions">
/// The started policy (enhanced authorization) sessions, keyed by session handle. Populated by
/// <c>TPM2_StartAuthSession()</c>, driven by the <c>TPM2_Policy*()</c> command family (each advancing the
/// session's policyDigest), read by <c>TPM2_PolicyGetDigest()</c>, and released by <c>TPM2_FlushContext()</c>
/// (TPM 2.0 Library Part 1, clause 17.7).
/// </param>
/// <param name="NextObjectHandle">
/// The handle the next created transient object receives, advanced on each <c>TPM2_CreatePrimary()</c>. Starts
/// at <see cref="TransientHandleBase"/> (the base of the <c>TPM_HT_TRANSIENT</c> range, TPM 2.0 Library Part 2,
/// clause 7.2).
/// </param>
/// <param name="NextSessionHandle">
/// The handle the next started policy session receives, advanced on each <c>TPM2_StartAuthSession()</c>. Starts
/// at <see cref="PolicySessionHandleBase"/> (the base of the <c>TPM_HT_POLICY_SESSION</c> range, TPM 2.0 Library
/// Part 2, clause 7.2), disjoint from the transient-object range so a session handle never collides with an object.
/// </param>
/// <param name="HmacSessions">
/// The started bound HMAC sessions with parameter encryption, keyed by session handle. Populated by
/// <c>TPM2_StartAuthSession()</c> for an HMAC session, driven by encrypt-attributed commands (each rolling the
/// session's nonceTPM), and released by <c>TPM2_FlushContext()</c> (TPM 2.0 Library Part 1, clauses 17.6 and 19).
/// </param>
/// <param name="NextHmacSessionHandle">
/// The handle the next started HMAC session receives, advanced on each HMAC <c>TPM2_StartAuthSession()</c>. Starts
/// at <see cref="HmacSessionHandleBase"/> (the base of the <c>TPM_HT_HMAC_SESSION</c> range, TPM 2.0 Library Part
/// 2, clause 7.2), disjoint from the policy-session and transient-object ranges.
/// </param>
/// <param name="NextAction">The effectful action the runner must execute next; <see cref="NullAction.Instance"/> when none.</param>
/// <param name="ResponseIntent">The logical response produced by the last command, or <see langword="null"/> when none (e.g. after <c>_TPM_Init</c>).</param>
public sealed record TpmSimulatorState(
    string TpmId,
    TpmLifecyclePhase Phase,
    TpmSelfTestBehavior ConfiguredSelfTest,
    TpmSelfTestStatus SelfTest,
    TpmSuConstants? LastOrderlyShutdown,
    ulong Clock,
    ulong Time,
    uint ResetCount,
    uint TimeEpoch,
    uint RestartCount,
    TpmiYesNo ClockSafe,
    ulong ClockAdvanceQuantumMs,
    uint FailedTries,
    uint MaxTries,
    uint RecoveryTime,
    uint LockoutRecovery,
    Tpm2bAuth LockoutAuth,
    bool LockoutAuthEnabled,
    ulong LastFailedTriesRecoveryTime,
    ulong LastLockoutAuthFailureTime,
    ImmutableDictionary<TpmiRhNvIndex, NvIndexState> NvIndexes,
    ulong NvCounterHighWaterMark,
    Tpm2bAuth OwnerAuth,
    Tpm2bAuth EndorsementAuth,
    Tpm2bAuth PlatformAuth,
    Tpm2bDigest OwnerAuthPolicy,
    TpmiAlgHash OwnerAuthPolicyHashAlg,
    Tpm2bDigest EndorsementAuthPolicy,
    TpmiAlgHash EndorsementAuthPolicyHashAlg,
    Tpm2bDigest PlatformAuthPolicy,
    TpmiAlgHash PlatformAuthPolicyHashAlg,
    Tpm2bDigest LockoutAuthPolicy,
    TpmiAlgHash LockoutAuthPolicyHashAlg,
    bool PhEnable,
    bool ShEnable,
    bool EhEnable,
    bool PhEnableNV,
    bool DisableClear,
    StorageProofSeed StorageProofSeed,
    ImmutableDictionary<TpmiDhObject, TransientKeyState> TransientObjects,
    ImmutableDictionary<TpmiDhPersistent, TransientKeyState> PersistentObjects,
    ImmutableDictionary<TpmiDhObject, SealedObjectState> LoadedSealedObjects,
    PcrBankState Sha256PcrBank,
    uint PcrUpdateCounter,
    ImmutableDictionary<TpmiShPolicy, PolicySessionState> PolicySessions,
    ImmutableDictionary<TpmiShHmac, HmacSessionState> HmacSessions,
    uint NextObjectHandle,
    uint NextSessionHandle,
    uint NextHmacSessionHandle,
    PdaAction NextAction,
    TpmResponseIntent? ResponseIntent)
{
    /// <summary>The default <see cref="MaxTries"/> for a freshly powered-off simulated TPM.</summary>
    public const uint DefaultMaxTries = 32;

    /// <summary>
    /// The digest size, in octets, of the hash this simulated TPM uses to protect the integrity of a saved
    /// context — SHA-256 here — and therefore two things at once: the width of a hierarchy proof (TPM 2.0
    /// Library Part 1, clause 12.5) and the largest authorization value a hierarchy may be given.
    /// </summary>
    /// <remarks>
    /// A hierarchy has no Name algorithm, so the general authValue bound "not larger than the digest size of the
    /// algorithm used to compute the Name of the object" (Part 1, clause 17.6.4.2) has nothing to bind to; the
    /// same clause names the substitute for such an entity — "the hash algorithm used for context integrity" —
    /// which Part 3, clause 24.8.1 restates as <c>TPM2_HierarchyChangeAuth()</c>'s own rule with a worked
    /// example. It is one implementation-selected constant for the whole TPM, not a per-hierarchy value, which is
    /// why it sizes both <see cref="StorageProofSeed"/> and the <c>newAuth</c> gate.
    /// </remarks>
    public const int ContextIntegrityDigestSize = 32;

    /// <summary>
    /// The shared Empty-Buffer session key: what a session that is neither bound nor salted carries
    /// (TPM 2.0 Library Part 1, clause 17.6.9 — no KDFa runs at all). Backed by
    /// <see cref="EmptyMemoryOwner"/>, so the one instance is safe to alias across every such session
    /// and immune to disposal.
    /// </summary>
    public static SymmetricKeyMemory EmptySessionKey { get; } = new(EmptyMemoryOwner.Instance, TpmTags.SessionKey);

    /// <summary>
    /// The base handle of the <c>TPM_HT_TRANSIENT</c> range (TPM 2.0 Library Part 2, clause 7.2): the handle the
    /// first created transient object receives.
    /// </summary>
    public const uint TransientHandleBase = 0x8000_0000;

    /// <summary>
    /// The base handle of the <c>TPM_HT_PERSISTENT</c> range (TPM 2.0 Library Part 2, clause 7.2): a persistent
    /// handle has the most-significant octet <c>0x81</c>. <c>TPM2_EvictControl()</c> assigns handles in this range.
    /// </summary>
    public const uint PersistentHandleBase = 0x8100_0000;

    /// <summary>
    /// The base handle of the <c>TPM_HT_POLICY_SESSION</c> range (TPM 2.0 Library Part 2, clause 7.2): a policy
    /// session handle has the most-significant octet <c>0x03</c>. <c>TPM2_StartAuthSession()</c> assigns handles in
    /// this range, disjoint from the <c>TPM_HT_TRANSIENT</c> object range (<see cref="TransientHandleBase"/>).
    /// </summary>
    public const uint PolicySessionHandleBase = 0x0300_0000;

    /// <summary>
    /// The base handle of the <c>TPM_HT_HMAC_SESSION</c> range (TPM 2.0 Library Part 2, clause 7.2): an HMAC
    /// session handle has the most-significant octet <c>0x02</c>. <c>TPM2_StartAuthSession()</c> assigns HMAC
    /// session handles in this range, disjoint from the policy-session (<see cref="PolicySessionHandleBase"/>) and
    /// transient-object (<see cref="TransientHandleBase"/>) ranges so a handle never collides across kinds.
    /// </summary>
    public const uint HmacSessionHandleBase = 0x0200_0000;

    /// <summary>The default <see cref="RecoveryTime"/> in seconds for a freshly powered-off simulated TPM.</summary>
    public const uint DefaultRecoveryTimeSeconds = 7200;

    /// <summary>The default <see cref="LockoutRecovery"/> in seconds for a freshly powered-off simulated TPM.</summary>
    public const uint DefaultLockoutRecoverySeconds = 86400;

    /// <summary>
    /// The default <see cref="ClockAdvanceQuantumMs"/> for a freshly powered-off simulated TPM: one millisecond
    /// per dispatched command.
    /// </summary>
    public const ulong DefaultClockAdvanceQuantumMs = 1UL;

    /// <summary>
    /// Gets a value indicating whether the TPM is in dictionary-attack Lockout mode, i.e. the failure
    /// counter has reached the tolerated maximum (TPM 2.0 Library Part 1, clause 17.8.3). The spec
    /// states <c>failedTries == maxTries</c>; this uses <c>&gt;=</c> defensively so an overshoot can
    /// never read as "out of lockout". <see cref="MaxTries"/> zero is fail-CLOSED, not disabled: with
    /// <see cref="FailedTries"/> a <see cref="uint"/> (always <c>&gt;= 0</c>), <c>FailedTries &gt;= 0</c>
    /// holds unconditionally, so the TPM is permanently in Lockout mode until <see cref="MaxTries"/> is
    /// raised again by a lockoutAuth-authorized <c>TPM2_DictionaryAttackParameters()</c> — matching the
    /// reference, which treats <c>maxTries == 0</c> as permanently locked rather than DA protection
    /// disabled. <c>TPM2_DictionaryAttackLockReset()</c> is not itself gated by this property (clause
    /// 25.2), so it remains callable regardless.
    /// </summary>
    public bool IsInLockout => FailedTries >= MaxTries;

    /// <summary>
    /// Gets a value indicating whether <paramref name="hierarchy"/> is one of the four permanent handles that
    /// carry their own authValue and authorization policy — <c>TPM_RH_OWNER</c>, <c>TPM_RH_ENDORSEMENT</c>,
    /// <c>TPM_RH_PLATFORM</c>, <c>TPM_RH_LOCKOUT</c> — that is, the value set of <c>TPMI_RH_HIERARCHY_AUTH</c>
    /// (TPM 2.0 Library Part 3, clause 24.8.2), which is also <c>TPMI_RH_HIERARCHY_POLICY</c>'s (clause 24.3.2)
    /// less the Authenticated Countdown Timer range this simulator does not model.
    /// </summary>
    /// <param name="hierarchy">The handle to classify.</param>
    /// <returns><see langword="true"/> when the handle names one of those four hierarchies.</returns>
    public static bool IsHierarchyAuthHandle(uint hierarchy) =>
        hierarchy is (uint)TpmRh.TPM_RH_OWNER or (uint)TpmRh.TPM_RH_ENDORSEMENT or (uint)TpmRh.TPM_RH_PLATFORM or (uint)TpmRh.TPM_RH_LOCKOUT;

    /// <summary>
    /// Gets a value indicating whether <paramref name="hierarchy"/> is one of the two handles that can authorize
    /// an owner change — <c>TPM_RH_LOCKOUT</c> or <c>TPM_RH_PLATFORM</c> — that is, the value set of
    /// <c>TPMI_RH_CLEAR</c>, which <c>TPM2_Clear()</c> and <c>TPM2_ClearControl()</c> share (TPM 2.0 Library
    /// Part 3, clauses 24.6.2 and 24.7.2).
    /// </summary>
    /// <param name="hierarchy">The handle to classify.</param>
    /// <returns><see langword="true"/> when the handle can authorize a clear or its control.</returns>
    public static bool IsClearAuthHandle(uint hierarchy) =>
        hierarchy is (uint)TpmRh.TPM_RH_LOCKOUT or (uint)TpmRh.TPM_RH_PLATFORM;

    /// <summary>
    /// Gets a value indicating whether <paramref name="hierarchy"/> is one of the three hierarchies that own an
    /// enable — <c>TPM_RH_OWNER</c>, <c>TPM_RH_ENDORSEMENT</c>, <c>TPM_RH_PLATFORM</c> — that is, the value set
    /// of <c>TPMI_RH_BASE_HIERARCHY</c>, the type of <c>TPM2_HierarchyControl()</c>'s authorization handle
    /// (TPM 2.0 Library Part 3, clause 24.2.2). The lockout entity is deliberately outside it: lockout owns no
    /// hierarchy and so can neither enable nor disable one.
    /// </summary>
    /// <param name="hierarchy">The handle to classify.</param>
    /// <returns><see langword="true"/> when the handle names a base hierarchy.</returns>
    public static bool IsBaseHierarchyHandle(uint hierarchy) =>
        hierarchy is (uint)TpmRh.TPM_RH_OWNER or (uint)TpmRh.TPM_RH_ENDORSEMENT or (uint)TpmRh.TPM_RH_PLATFORM;

    /// <summary>
    /// Gets a value indicating whether <paramref name="enable"/> names one of the four enables
    /// <c>TPM2_HierarchyControl()</c> can write — the value set of <c>TPMI_RH_ENABLES</c>, which is
    /// <see cref="IsBaseHierarchyHandle"/>'s set plus <c>TPM_RH_PLATFORM_NV</c> (TPM 2.0 Library Part 3, clause
    /// 24.2.2). A handle appearing here names a BIT, not an entity being authorized.
    /// </summary>
    /// <param name="enable">The handle to classify.</param>
    /// <returns><see langword="true"/> when the handle names a writable enable.</returns>
    public static bool IsEnablesHandle(uint enable) =>
        IsBaseHierarchyHandle(enable) || enable == (uint)TpmRh.TPM_RH_PLATFORM_NV;

    /// <summary>
    /// Gets a value indicating whether <paramref name="hierarchy"/> is one of the four handles a primary object
    /// can be created under — <c>TPM_RH_OWNER</c>, <c>TPM_RH_ENDORSEMENT</c>, <c>TPM_RH_PLATFORM</c>, or
    /// <c>TPM_RH_NULL</c> — that is, the value set of <c>TPMI_RH_HIERARCHY</c>, the type of
    /// <c>TPM2_CreatePrimary()</c>'s <c>primaryHandle</c> (TPM 2.0 Library Part 2, clause 9.20).
    /// </summary>
    /// <remarks>
    /// It differs from <see cref="IsHierarchyAuthHandle"/> at both ends: the null hierarchy has no authValue of
    /// its own to administer but does hold objects, while the lockout entity has an authValue but holds none.
    /// </remarks>
    /// <param name="hierarchy">The handle to classify.</param>
    /// <returns><see langword="true"/> when the handle can parent a primary object.</returns>
    public static bool IsPrimaryHierarchyHandle(uint hierarchy) =>
        IsBaseHierarchyHandle(hierarchy) || hierarchy == (uint)TpmRh.TPM_RH_NULL;

    /// <summary>
    /// Resolves the authorization value <paramref name="hierarchy"/> is authorized by, so a caller compares
    /// against the one field the handle actually names instead of choosing it at each call site.
    /// </summary>
    /// <remarks>
    /// A handle outside <see cref="IsHierarchyAuthHandle"/>'s set answers <see langword="false"/> with the empty
    /// value, so the handle-set check and the field selection cannot drift apart: a caller that ignored the
    /// return value would be comparing a caller-supplied secret against the Empty Buffer, which the
    /// <see langword="false"/> result exists to prevent.
    /// </remarks>
    /// <param name="hierarchy">The hierarchy handle whose authValue is wanted.</param>
    /// <param name="authValue">The resolved authValue carrier, borrowed from this state (the state stays the owner), or the shared empty carrier when the handle names no hierarchy.</param>
    /// <returns><see langword="true"/> when <paramref name="hierarchy"/> names a hierarchy that has an authValue.</returns>
    public bool TryGetHierarchyAuthValue(uint hierarchy, out Tpm2bAuth authValue)
    {
        authValue = hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => OwnerAuth,
            (uint)TpmRh.TPM_RH_ENDORSEMENT => EndorsementAuth,
            (uint)TpmRh.TPM_RH_PLATFORM => PlatformAuth,
            (uint)TpmRh.TPM_RH_LOCKOUT => LockoutAuth,
            _ => Tpm2bAuth.Empty
        };

        return IsHierarchyAuthHandle(hierarchy);
    }

    /// <summary>
    /// Resolves the authorization policy digest and its hash algorithm for <paramref name="hierarchy"/>, the
    /// pair <c>TPM2_SetPrimaryPolicy()</c> installs and every policy-session authorization of that hierarchy is
    /// measured against (TPM 2.0 Library Part 3, clause 24.3.1).
    /// </summary>
    /// <remarks>
    /// An empty digest is the disabled state, not a wildcard: "When the authPolicy is empty, it cannot match any
    /// policyDigest value so the use of authPolicy is disabled" (TPM 2.0 Library Part 1, clause 11.2, Table 5).
    /// A handle outside <see cref="IsHierarchyAuthHandle"/>'s set therefore answers <see langword="false"/> with
    /// that same empty, match-nothing digest, so the unresolved case fails closed either way.
    /// </remarks>
    /// <param name="hierarchy">The hierarchy handle whose policy is wanted.</param>
    /// <param name="authPolicy">The resolved policy digest — a borrowed reference to the state's own carrier, or the empty sentinel when the handle names no hierarchy. The caller reads it and never disposes it.</param>
    /// <param name="authPolicyHashAlg">
    /// The hash algorithm <paramref name="authPolicy"/> is expressed under, <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/>
    /// whenever that digest is empty.
    /// </param>
    /// <returns><see langword="true"/> when <paramref name="hierarchy"/> names a hierarchy that has a policy slot.</returns>
    public bool TryGetHierarchyAuthPolicy(uint hierarchy, out Tpm2bDigest authPolicy, out TpmiAlgHash authPolicyHashAlg)
    {
        (Tpm2bDigest Digest, TpmiAlgHash HashAlg) resolved = hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => (Digest: OwnerAuthPolicy, HashAlg: OwnerAuthPolicyHashAlg),
            (uint)TpmRh.TPM_RH_ENDORSEMENT => (Digest: EndorsementAuthPolicy, HashAlg: EndorsementAuthPolicyHashAlg),
            (uint)TpmRh.TPM_RH_PLATFORM => (Digest: PlatformAuthPolicy, HashAlg: PlatformAuthPolicyHashAlg),
            (uint)TpmRh.TPM_RH_LOCKOUT => (Digest: LockoutAuthPolicy, HashAlg: LockoutAuthPolicyHashAlg),
            _ => (Digest: Tpm2bDigest.Empty, HashAlg: TpmiAlgHash.FromValue(TpmAlgIdConstants.TPM_ALG_NULL))
        };

        authPolicy = resolved.Digest;
        authPolicyHashAlg = resolved.HashAlg;

        return IsHierarchyAuthHandle(hierarchy);
    }

    /// <summary>
    /// Installs <paramref name="authValue"/> as <paramref name="hierarchy"/>'s authorization value — the write
    /// side of <see cref="TryGetHierarchyAuthValue"/>, so the handle-to-field mapping the two share is written
    /// once and cannot drift between the reading and the writing command (TPM 2.0 Library Part 3, clause 24.8.1
    /// enumerates the same four pairings).
    /// </summary>
    /// <remarks>
    /// A handle outside <see cref="IsHierarchyAuthHandle"/>'s set answers the state unchanged rather than
    /// throwing: the caller has already refused such a handle, and silently ignoring it is the direction that
    /// cannot install a secret against an entity that has no slot for one. Ownership of
    /// <paramref name="authValue"/> transfers here on every arm — a named hierarchy's arm disposes the field
    /// it replaces and installs the new carrier; the unmatched arm disposes the carrier that has no slot to
    /// live in, so no path leaks it.
    /// </remarks>
    /// <param name="hierarchy">The hierarchy handle whose authValue is replaced.</param>
    /// <param name="authValue">The replacement authorization value in an owned carrier, trailing zeros already removed; ownership transfers to this call.</param>
    /// <returns>The state with that hierarchy's authValue replaced.</returns>
    [SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope",
        Justification = "Ownership of authValue transfers to the returned state's hierarchy-auth field, which the next rotation, TPM2_Clear(), or the simulator's teardown walk releases; the outgoing field is disposed here before the with-copy replaces it.")]
    public TpmSimulatorState WithHierarchyAuthValue(uint hierarchy, Tpm2bAuth authValue)
    {
        ArgumentNullException.ThrowIfNull(authValue);

        //The unmatched arm resolves the INCOMING carrier as the outgoing one: it has no slot to live
        //in, so releasing it here is what keeps the no-op return leak-free.
        Tpm2bAuth outgoing = hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => OwnerAuth,
            (uint)TpmRh.TPM_RH_ENDORSEMENT => EndorsementAuth,
            (uint)TpmRh.TPM_RH_PLATFORM => PlatformAuth,
            (uint)TpmRh.TPM_RH_LOCKOUT => LockoutAuth,
            _ => authValue
        };
        outgoing.Dispose();

        return hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => this with { OwnerAuth = authValue },
            (uint)TpmRh.TPM_RH_ENDORSEMENT => this with { EndorsementAuth = authValue },
            (uint)TpmRh.TPM_RH_PLATFORM => this with { PlatformAuth = authValue },
            (uint)TpmRh.TPM_RH_LOCKOUT => this with { LockoutAuth = authValue },
            _ => this
        };
    }

    /// <summary>
    /// Installs <paramref name="authPolicy"/> and <paramref name="authPolicyHashAlg"/> as
    /// <paramref name="hierarchy"/>'s authorization policy — the write side of
    /// <see cref="TryGetHierarchyAuthPolicy"/>, and the whole effect of <c>TPM2_SetPrimaryPolicy()</c> (TPM 2.0
    /// Library Part 3, clause 24.3.1: "The policy that is changed is the policy associated with authHandle").
    /// </summary>
    /// <remarks>
    /// The digest and its algorithm travel together because neither is meaningful alone: a policy digest is only
    /// comparable against a policy session whose own hash matches, and the algorithm is
    /// <see cref="TpmAlgIdConstants.TPM_ALG_NULL"/> exactly when the digest is the Empty Buffer that disables
    /// policy authorization altogether. A handle outside <see cref="IsHierarchyAuthHandle"/>'s set answers the
    /// state unchanged, on the same fail-closed reasoning as <see cref="WithHierarchyAuthValue"/>. Ownership of
    /// <paramref name="authPolicy"/> transfers here on every arm — a named hierarchy's arm disposes the digest
    /// it replaces and installs the new carrier; the unmatched arm disposes the carrier that has no slot to live
    /// in, so no path leaks it.
    /// </remarks>
    /// <param name="hierarchy">The hierarchy handle whose policy is replaced.</param>
    /// <param name="authPolicy">The replacement policy digest in an owned carrier, or the empty sentinel to disable policy authorization; ownership transfers to this call.</param>
    /// <param name="authPolicyHashAlg">The hash algorithm <paramref name="authPolicy"/> is expressed under.</param>
    /// <returns>The state with that hierarchy's policy replaced.</returns>
    [SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope",
        Justification = "Ownership of authPolicy transfers to the returned state's hierarchy-policy field, which the next installation, a Reset that empties the platform policy, or the simulator's teardown walk releases; the outgoing field is disposed here before the with-copy replaces it.")]
    public TpmSimulatorState WithHierarchyAuthPolicy(uint hierarchy, Tpm2bDigest authPolicy, TpmiAlgHash authPolicyHashAlg)
    {
        ArgumentNullException.ThrowIfNull(authPolicy);

        //The unmatched arm resolves the INCOMING carrier as the outgoing one: it has no slot to live
        //in, so releasing it here is what keeps the no-op return leak-free.
        Tpm2bDigest outgoing = hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => OwnerAuthPolicy,
            (uint)TpmRh.TPM_RH_ENDORSEMENT => EndorsementAuthPolicy,
            (uint)TpmRh.TPM_RH_PLATFORM => PlatformAuthPolicy,
            (uint)TpmRh.TPM_RH_LOCKOUT => LockoutAuthPolicy,
            _ => authPolicy
        };
        outgoing.Dispose();

        return hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => this with { OwnerAuthPolicy = authPolicy, OwnerAuthPolicyHashAlg = authPolicyHashAlg },
            (uint)TpmRh.TPM_RH_ENDORSEMENT => this with { EndorsementAuthPolicy = authPolicy, EndorsementAuthPolicyHashAlg = authPolicyHashAlg },
            (uint)TpmRh.TPM_RH_PLATFORM => this with { PlatformAuthPolicy = authPolicy, PlatformAuthPolicyHashAlg = authPolicyHashAlg },
            (uint)TpmRh.TPM_RH_LOCKOUT => this with { LockoutAuthPolicy = authPolicy, LockoutAuthPolicyHashAlg = authPolicyHashAlg },
            _ => this
        };
    }

    /// <summary>
    /// Gets a value indicating whether the enable governing <paramref name="hierarchy"/> is currently SET, the
    /// precondition on which "neither the corresponding authValue nor authPolicy can authorize operations"
    /// turns (TPM 2.0 Library Part 1, clause 11.2).
    /// </summary>
    /// <remarks>
    /// This answers the enable question only. <c>TPM_RH_LOCKOUT</c> and <c>TPM_RH_NULL</c> have no enable bit at
    /// all — lockout is governed by <see cref="LockoutAuthEnabled"/> and the dictionary-attack counters (clause
    /// 11.7), not by <c>TPMA_STARTUP_CLEAR</c> — so they answer <see langword="true"/>, as does any handle that
    /// names no hierarchy. Whether the handle is admissible for a given command is the caller's separate check
    /// (<see cref="IsHierarchyAuthHandle"/> for the commands whose interface type is
    /// <c>TPMI_RH_HIERARCHY_AUTH</c>).
    /// </remarks>
    /// <param name="hierarchy">The hierarchy handle whose enable is wanted.</param>
    /// <returns><see langword="true"/> when the hierarchy's authorizations and objects are usable.</returns>
    public bool IsHierarchyEnabled(uint hierarchy) =>
        hierarchy switch
        {
            (uint)TpmRh.TPM_RH_OWNER => ShEnable,
            (uint)TpmRh.TPM_RH_ENDORSEMENT => EhEnable,
            (uint)TpmRh.TPM_RH_PLATFORM => PhEnable,
            (uint)TpmRh.TPM_RH_PLATFORM_NV => PhEnableNV,
            _ => true
        };

    /// <summary>
    /// Creates the initial state of a simulated TPM: powered off, awaiting <c>_TPM_Init</c>, with the
    /// default dictionary-attack parameters and clock/reset counters all at their zero baseline.
    /// </summary>
    /// <remarks>
    /// This is the simulator's manufacture-time initialization, so it is where the values no
    /// <c>TPM2_Startup()</c> form ever restores are fixed: every hierarchy authValue and authorization policy
    /// starts empty, all four enables start SET, and <see cref="DisableClear"/> starts
    /// <see langword="false"/> — <c>TPM2_Clear()</c> is permitted out of the box (TPM 2.0 Library Part 1,
    /// clause 11.8.2).
    /// </remarks>
    /// <param name="tpmId">The stable identifier of this simulated TPM.</param>
    /// <param name="configuredSelfTest">The modelled self-test behaviour.</param>
    /// <param name="clockAdvanceQuantumMs">The fixed per-command clock advance, in milliseconds.</param>
    /// <param name="initialTimeEpoch">
    /// The <see cref="TimeEpoch"/> value drawn from the injected entropy seam at construction, before any
    /// <c>TPM2_Startup()</c> has run; defaults to zero for a caller that does not need a distinct initial
    /// value (for example a direct, entropy-free construction in a unit test).
    /// </param>
    /// <param name="initialStorageProofSeed">
    /// The <see cref="StorageProofSeed"/> the created state starts from, in a carrier whose ownership
    /// transfers to it. The default — the shared <see cref="Automata.StorageProofSeed.Empty"/> sentinel — IS
    /// the manufacture model: while it holds, proof derivation falls back to the platform proof seed, so
    /// every hierarchy's proof is what one shared seed yields until <c>TPM2_Clear()</c> generates a real
    /// storage seed and parts them. A supplied carrier overrides that fallback from the start, for a caller
    /// that fixes the storage seed deterministically.
    /// </param>
    /// <returns>A powered-off state.</returns>
    public static TpmSimulatorState PoweredOff(
        string tpmId,
        TpmSelfTestBehavior configuredSelfTest,
        ulong clockAdvanceQuantumMs = DefaultClockAdvanceQuantumMs,
        uint initialTimeEpoch = 0u,
        StorageProofSeed? initialStorageProofSeed = null) =>
        new(
            tpmId,
            TpmLifecyclePhase.PoweredOff,
            configuredSelfTest,
            TpmSelfTestStatus.NotRun,
            null,
            0ul,
            0ul,
            0u,
            initialTimeEpoch,
            0u,
            TpmiYesNo.Yes,
            clockAdvanceQuantumMs,
            0u,
            DefaultMaxTries,
            DefaultRecoveryTimeSeconds,
            DefaultLockoutRecoverySeconds,
            Tpm2bAuth.Empty,
            true,
            0ul,
            0ul,
            ImmutableDictionary<TpmiRhNvIndex, NvIndexState>.Empty,
            0ul,
            Tpm2bAuth.Empty,
            Tpm2bAuth.Empty,
            Tpm2bAuth.Empty,
            Tpm2bDigest.Empty,
            TpmiAlgHash.FromValue(TpmAlgIdConstants.TPM_ALG_NULL),
            Tpm2bDigest.Empty,
            TpmiAlgHash.FromValue(TpmAlgIdConstants.TPM_ALG_NULL),
            Tpm2bDigest.Empty,
            TpmiAlgHash.FromValue(TpmAlgIdConstants.TPM_ALG_NULL),
            Tpm2bDigest.Empty,
            TpmiAlgHash.FromValue(TpmAlgIdConstants.TPM_ALG_NULL),
            true,
            true,
            true,
            true,
            false,
            initialStorageProofSeed ?? Automata.StorageProofSeed.Empty,
            ImmutableDictionary<TpmiDhObject, TransientKeyState>.Empty,
            ImmutableDictionary<TpmiDhPersistent, TransientKeyState>.Empty,
            ImmutableDictionary<TpmiDhObject, SealedObjectState>.Empty,
            PcrBankState.Sha256AtReset(),
            0u,
            ImmutableDictionary<TpmiShPolicy, PolicySessionState>.Empty,
            ImmutableDictionary<TpmiShHmac, HmacSessionState>.Empty,
            TransientHandleBase,
            PolicySessionHandleBase,
            HmacSessionHandleBase,
            NullAction.Instance,
            null);
}
