using System;

namespace Verifiable.Fido2.Ctap;

/// <summary>
/// Encodes the resolved <c>credProtect</c>/<c>hmac-secret</c>/<c>minPinLength</c>/<c>hmac-secret-mc</c>
/// authenticator extension output values into the authData <c>extensions</c> CBOR map bytes — the
/// authenticator-side operation.
/// </summary>
/// <param name="credProtect">
/// The <c>credProtect</c> output value to emit (CTAP 2.3, section 12.1, line 12632's MUST — the level
/// the authenticator set for the created credential), or <see langword="null"/> to omit the key
/// entirely (section 12.1, line 12648's MUST NOT — no unsolicited output).
/// </param>
/// <param name="hmacSecret">
/// The <c>hmac-secret</c> annotation to emit (CTAP 2.3, section 12.7, snapshot lines 13198-13201), or
/// <see langword="null"/> to omit the key entirely (the mc request did not carry a literal
/// <see langword="true"/> — contract R3). This authenticator's own call site never supplies
/// <see langword="false"/> (snapshot lines 13204-13209 are antecedent-false-by-construction here, since
/// CredRandom generation never fails) — the parameter accepts it anyway: the codec is faithful to
/// whatever value it is given, mirroring the waveep <c>epAtt</c> R9 precedent.
/// </param>
/// <param name="minPinLength">
/// The <c>minPinLength</c> output value to emit (CTAP 2.3, section 12.5 — the current minimum PIN
/// length in Unicode code points, present only for an authorized <c>rp.id</c>), or
/// <see langword="null"/> to omit the key entirely (an absent request, or an unauthorized <c>rp.id</c>,
/// which section 12.5 itself resolves as silent omission inside an otherwise-successful response).
/// </param>
/// <param name="hmacSecretMc">
/// The encrypted <c>hmac-secret-mc</c> output bytes to emit (CTAP 2.3, section 12.8, snapshot line
/// 13408: "Same as the hmac secret extension's getAssertion output" — contract R6, a value produced by
/// the same routine section 12.7's <c>authenticatorGetAssertion</c> processing uses), or
/// <see langword="null"/> to omit the key entirely (the mc request did not pair
/// <c>hmac-secret-mc</c> with a granted <c>hmac-secret</c>). Borrowed, not owned — the caller retains
/// custody of the underlying pooled buffer.
/// </param>
/// <returns>
/// The encoded <c>extensions</c> map bytes, wrapped in a <see cref="TaggedMemory{T}"/>;
/// <see cref="TaggedMemory{T}.Empty"/> — never an encoded empty CBOR map — when every parameter is
/// <see langword="null"/>.
/// </returns>
/// <remarks>
/// <para>
/// <see href="https://fidoalliance.org/specs/fido-v2.3-ps-20260226/fido-client-to-authenticator-protocol-v2.3-ps-20260226.html#authenticatorMakeCredential">
/// CTAP 2.3, section 6.1.2: authenticatorMakeCredential Algorithm</see>, the extensions-processing step
/// (lines 3548-3559): "Authenticator extension outputs generated by the authenticator extension
/// processing are returned in the authenticator data." <c>credProtect</c>/<c>minPinLength</c> are
/// registration-only (neither defines an <c>authenticatorGetAssertion</c> output);
/// <c>hmac-secret</c>/<c>hmac-secret-mc</c> are the first two extensions this delegate carries whose
/// underlying crypto is <c>authenticatorGetAssertion</c>-shaped (section 12.7's processing algorithm)
/// even though this delegate's own OWN call site is <c>authenticatorMakeCredential</c>-only.
/// </para>
/// <para>
/// The concrete CBOR codec is supplied at the composition edge, keeping <c>Verifiable.Fido2</c>
/// serialization-agnostic — mirrors <see cref="EncodeCredentialPublicKeyDelegate"/>'s established seam
/// shape. The shipped default, <c>Verifiable.Cbor.Ctap.CtapMakeCredentialExtensionOutputsCborWriter.Write</c>,
/// is method-group-compatible with this delegate. The returned bytes and their emptiness together
/// determine both the argument <see cref="AuthenticatorDataWriter.Write"/>'s own <c>extensions</c>
/// parameter receives and the <c>ED</c> flag bit the caller sets to match — <c>AuthenticatorDataWriter</c>'s
/// own fail-closed check enforces the two agree.
/// </para>
/// </remarks>
public delegate TaggedMemory<byte> EncodeCtapMakeCredentialExtensionOutputsDelegate(
    int? credProtect, bool? hmacSecret, int? minPinLength, ReadOnlyMemory<byte>? hmacSecretMc);
