using System.Text;
using Verifiable.Xml;

namespace Verifiable.Tests.Xml;

/// <summary>
/// Proofs that canonicalization is idempotent over every shared fixture input document of
/// <see cref="XmlCanonicalizationFixtureInputs"/>: the canonical octets of a document, parsed and
/// canonicalized again under the same member of <see cref="XmlCanonicalizationAlgorithm"/>, reproduce
/// themselves byte for byte. The join-URI path fixtures of <see cref="XmlBaseUriJoinTests"/> are not
/// documents and the section 3.6 encoding-example input is refused at parse, so neither has a canonical
/// form to reproduce.
/// </summary>
[TestClass]
internal sealed class XmlCanonicalizationIdempotenceTests
{
    private static byte[] Canonicalize(byte[] documentOctets, XmlCanonicalizationAlgorithm algorithm, string fixtureName)
    {
        bool isParsed = XmlNodeTable.TryParse(documentOctets, BaseMemoryPool.Shared, out XmlNodeTable? table, out XmlReadError readError);
        Assert.IsTrue(isParsed, $"Fixture '{fixtureName}' must parse but was refused with {readError.Failure} at offset {readError.ByteOffset}.");
        using(table)
        {
            bool isCanonicalized = XmlCanonicalization.TryCanonicalize(table!, XmlNodeSet.WholeDocument(table!), algorithm, BaseMemoryPool.Shared, out PooledMemory? canonicalOctets, out XmlCanonicalizationError error);
            Assert.IsTrue(isCanonicalized, $"Fixture '{fixtureName}' must canonicalize under {algorithm} but was refused with {error.Failure}.");
            using(canonicalOctets)
            {
                return canonicalOctets!.AsReadOnlySpan().ToArray();
            }
        }
    }


    private static void AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm algorithm)
    {
        foreach((string name, string document) in XmlCanonicalizationFixtureInputs.AllDocuments)
        {
            byte[] first = Canonicalize(Encoding.UTF8.GetBytes(document), algorithm, name);
            byte[] second = Canonicalize(first, algorithm, name);

            Assert.AreSequenceEqual(first, second, $"Fixture '{name}' must reproduce its canonical form byte for byte under {algorithm}.");
        }
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "it is the intent of this specification that if the text generated by
    /// canonicalizing a document according to this specification is itself parsed and canonicalized
    /// according to this specification, the text generated by the second canonicalization will be the same
    /// as that generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.CanonicalXml10"/> over every shared fixture input.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderCanonicalXml10()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.CanonicalXml10);
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "the text generated by the second canonicalization will be the same as that
    /// generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.CanonicalXml10WithComments"/> over every shared fixture
    /// input, the comments themselves surviving both passes unchanged.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderCanonicalXml10WithComments()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.CanonicalXml10WithComments);
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "the text generated by the second canonicalization will be the same as that
    /// generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.CanonicalXml11"/> over every shared fixture input.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderCanonicalXml11()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.CanonicalXml11);
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "the text generated by the second canonicalization will be the same as that
    /// generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.CanonicalXml11WithComments"/> over every shared fixture
    /// input, the comments themselves surviving both passes unchanged.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderCanonicalXml11WithComments()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.CanonicalXml11WithComments);
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "the text generated by the second canonicalization will be the same as that
    /// generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.ExclusiveCanonicalXml10"/> over every shared fixture input:
    /// a whole document canonicalized exclusively renders every namespace declaration where it is visibly
    /// utilized, and re-canonicalizing that rendering moves nothing.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderExclusiveCanonicalXml10()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.ExclusiveCanonicalXml10);
    }


    /// <summary>
    /// Proves the <see href="https://www.w3.org/TR/2008/REC-xml-c14n11-20080502/">Canonical XML 1.1</see>
    /// section 1.2 note — "the text generated by the second canonicalization will be the same as that
    /// generated by the first canonicalization" — under
    /// <see cref="XmlCanonicalizationAlgorithm.ExclusiveCanonicalXml10WithComments"/> over every shared
    /// fixture input, the comments themselves surviving both passes unchanged.
    /// </summary>
    [TestMethod]
    public void CanonicalFormReproducesItselfUnderExclusiveCanonicalXml10WithComments()
    {
        AssertCanonicalFormReproducesItself(XmlCanonicalizationAlgorithm.ExclusiveCanonicalXml10WithComments);
    }
}
