using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using Lumoin.Base;
using Verifiable.Foundation;

namespace Verifiable.Xml;

/// <summary>
/// Which arm of <c>GenericTimeStampType</c>'s <c>EncapsulatedTimeStamp</c>/<c>XMLTimeStamp</c> choice
/// (clause 5.1.4.3) a <see cref="XAdESTimeStampEntry"/> holds.
/// </summary>
public enum XAdESTimeStampEntryKind
{
    /// <summary>An <c>EncapsulatedTimeStamp</c> element: an RFC 3161 <c>TimeStampToken</c>, base64-encoded per <c>EncapsulatedPKIDataType</c>.</summary>
    EncapsulatedTimeStamp,

    /// <summary>An <c>XMLTimeStamp</c> element: an XML-encoded electronic time-stamp, carried unmodeled.</summary>
    XmlTimeStamp
}


/// <summary>
/// One member of <c>GenericTimeStampType</c>'s <c>EncapsulatedTimeStamp</c>/<c>XMLTimeStamp</c> choice
/// (clause 5.1.4.3, XA-5.1.4.3-2): exactly one of <see cref="EncapsulatedTimeStamp"/> or
/// <see cref="XmlTimeStamp"/> is meaningful, selected by <see cref="Kind"/> — the two-way dispatch
/// XA-5.1.4.3-5 states ("If the electronic time-stamp generated by the TSA is conformant to IETF RFC 3161
/// ... it shall be included within the EncapsulatedTimeStamp element. If ... encoded as XML then it shall be
/// included within XMLTimeStamp element"). <c>XMLTimeStamp</c>'s content is carried through
/// <see cref="XAdESUnmodeledContent"/> — this leaf never parses an XML
/// time-stamp format, and clause 6.3 restricts baseline time-stamp containers to RFC 3161 tokens only, so
/// <c>XMLTimeStamp</c> has no verification-side interpretation here regardless.
/// </summary>
public readonly struct XAdESTimeStampEntry: IEquatable<XAdESTimeStampEntry>
{
    /// <summary>Which arm of the choice this entry holds.</summary>
    public XAdESTimeStampEntryKind Kind { get; }

    /// <summary>The <c>EncapsulatedTimeStamp</c> payload; meaningful only when <see cref="Kind"/> is <see cref="XAdESTimeStampEntryKind.EncapsulatedTimeStamp"/>.</summary>
    public XAdESEncapsulatedPkiData EncapsulatedTimeStamp { get; }

    /// <summary>The <c>XMLTimeStamp</c> payload; meaningful only when <see cref="Kind"/> is <see cref="XAdESTimeStampEntryKind.XmlTimeStamp"/>.</summary>
    public XAdESUnmodeledContent XmlTimeStamp { get; }


    private XAdESTimeStampEntry(XAdESTimeStampEntryKind kind, XAdESEncapsulatedPkiData encapsulatedTimeStamp, XAdESUnmodeledContent xmlTimeStamp)
    {
        Kind = kind;
        EncapsulatedTimeStamp = encapsulatedTimeStamp;
        XmlTimeStamp = xmlTimeStamp;
    }


    /// <summary>Wraps an <c>EncapsulatedTimeStamp</c> payload.</summary>
    /// <param name="value">The read <c>EncapsulatedTimeStamp</c>.</param>
    /// <returns>The wrapped entry.</returns>
    internal static XAdESTimeStampEntry FromEncapsulatedTimeStamp(XAdESEncapsulatedPkiData value) => new(XAdESTimeStampEntryKind.EncapsulatedTimeStamp, value, default);


    /// <summary>Wraps an <c>XMLTimeStamp</c> payload.</summary>
    /// <param name="value">The unmodeled <c>XMLTimeStamp</c> content.</param>
    /// <returns>The wrapped entry.</returns>
    internal static XAdESTimeStampEntry FromXmlTimeStamp(XAdESUnmodeledContent value) => new(XAdESTimeStampEntryKind.XmlTimeStamp, default, value);


    /// <inheritdoc />
    [EditorBrowsable(EditorBrowsableState.Never)]
    public bool Equals(XAdESTimeStampEntry other) =>
        Kind == other.Kind
        && (Kind == XAdESTimeStampEntryKind.EncapsulatedTimeStamp ? EncapsulatedTimeStamp.Equals(other.EncapsulatedTimeStamp) : XmlTimeStamp.Equals(other.XmlTimeStamp));


    /// <inheritdoc />
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override bool Equals([NotNullWhen(true)] object? obj) => obj is XAdESTimeStampEntry other && Equals(other);


    /// <inheritdoc />
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override int GetHashCode() => Kind == XAdESTimeStampEntryKind.EncapsulatedTimeStamp ? HashCode.Combine(Kind, EncapsulatedTimeStamp) : HashCode.Combine(Kind, XmlTimeStamp);


    /// <inheritdoc />
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator ==(XAdESTimeStampEntry left, XAdESTimeStampEntry right) => left.Equals(right);


    /// <inheritdoc />
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator !=(XAdESTimeStampEntry left, XAdESTimeStampEntry right) => !left.Equals(right);
}


/// <summary>
/// The <c>EncapsulatedTimeStamp</c>/<c>XMLTimeStamp</c> choice-member recognition and reading
/// <see cref="XAdESTimeStamp"/> and <see cref="XAdESOtherTimeStamp"/> share — both restrictions of the
/// abstract <c>GenericTimeStampType</c> (clause 5.1.4.3) end in this same choice, differing only in how many
/// times it may occur (one-or-more for <c>XAdESTimeStampType</c>, exactly one for <c>OtherTimeStampType</c>)
/// — a difference each caller's own occurrence loop enforces, not this helper.
/// </summary>
internal static class XAdESGenericTimeStamp
{
    /// <summary>
    /// Tells whether an element is one of the two names the <c>EncapsulatedTimeStamp</c>/<c>XMLTimeStamp</c>
    /// choice permits.
    /// </summary>
    /// <param name="table">The node table.</param>
    /// <param name="elementIndex">The element to test.</param>
    /// <returns><see langword="true"/> when the element is a choice member.</returns>
    public static bool IsChoiceMember(XmlNodeTable table, int elementIndex)
    {
        return XmlSignatureModelGrammar.IsElement(table, elementIndex, XAdESIdentifiers.XAdESNamespaceV132Utf8, "EncapsulatedTimeStamp"u8)
            || XmlSignatureModelGrammar.IsElement(table, elementIndex, XAdESIdentifiers.XAdESNamespaceV132Utf8, "XMLTimeStamp"u8);
    }


    /// <summary>
    /// Reads one choice member, dispatching on its element name: <c>EncapsulatedTimeStamp</c> through
    /// <see cref="XAdESEncapsulatedPkiData.TryRead"/>; <c>XMLTimeStamp</c> through
    /// <see cref="XAdESUnmodeledContent.Read"/>, which cannot refuse. The caller has already confirmed the
    /// element is a choice member via <see cref="IsChoiceMember"/>.
    /// </summary>
    /// <param name="table">The node table.</param>
    /// <param name="elementIndex">The choice-member element.</param>
    /// <param name="pool">The pool an <c>EncapsulatedTimeStamp</c>'s decoded content is rented from.</param>
    /// <param name="owned">The caller's custody list. An <c>EncapsulatedTimeStamp</c>'s decoded content is
    /// appended as it is read, including on paths that subsequently refuse — the caller must dispose the
    /// list when this method returns <see langword="false"/>.</param>
    /// <param name="entry">The read entry on success.</param>
    /// <param name="error">The refusal on failure.</param>
    public static bool TryReadChoiceMember(XmlNodeTable table, int elementIndex, BaseMemoryPool pool, List<PooledMemory> owned, out XAdESTimeStampEntry entry, out XAdESReadError error)
    {
        if(XmlSignatureModelGrammar.IsElement(table, elementIndex, XAdESIdentifiers.XAdESNamespaceV132Utf8, "EncapsulatedTimeStamp"u8))
        {
            if(!XAdESEncapsulatedPkiData.TryRead(table, elementIndex, pool, owned, out XAdESEncapsulatedPkiData pkiData, out error))
            {
                entry = default;

                return false;
            }

            entry = XAdESTimeStampEntry.FromEncapsulatedTimeStamp(pkiData);
            error = default;

            return true;
        }

        entry = XAdESTimeStampEntry.FromXmlTimeStamp(XAdESUnmodeledContent.Read(table, elementIndex));
        error = default;

        return true;
    }
}
