using System.Collections.Immutable;
using System.Diagnostics;
using Verifiable.Core.Dcql;
using Verifiable.Cryptography;

namespace Verifiable.OAuth.Oid4Vp.Server;

/// <summary>
/// Server-side PAR input. Transitions the sentinel
/// <see cref="States.VerifierFlowFailedState"/> to
/// <see cref="States.VerifierParReceivedState"/>.
/// </summary>
/// <param name="FlowId">
/// The internal flow identifier. Generated by the PAR endpoint handler and kept
/// server-side only. Distinct from the external <c>request_uri</c> token carried
/// in <paramref name="Par"/>.
/// </param>
/// <param name="Par">The PAR response carrying the generated <c>request_uri</c>.</param>
/// <param name="Nonce">The transaction nonce to embed in the JAR.</param>
/// <param name="Query">The prepared DCQL query to embed in the JAR.</param>
/// <param name="DecryptionKeyId">
/// The identifier of the ephemeral private key for JWE decryption.
/// </param>
/// <param name="SigningKeyId">
/// The identifier of the signing key used to sign the JAR.
/// </param>
/// <param name="AllowedEncAlgorithms">
/// The content encryption algorithms the Verifier advertises in
/// <c>encrypted_response_enc_values_supported</c>. Carried through all states so the
/// <see cref="DecryptResponseAction"/> handler can validate the JWE <c>enc</c> header
/// against this set per
/// <see href="https://openid.net/specs/openid4vc-high-assurance-interoperability-profile-1_0.html">HAIP 1.0 §5.1</see>.
/// </param>
/// <param name="ReceivedAt">The UTC instant the PAR request was received.</param>
[DebuggerDisplay("ServerParReceived FlowId={FlowId} RequestUri={Par.RequestUri}")]
public sealed record ServerParReceived(
    string FlowId,
    ParResponse Par,
    TransactionNonce Nonce,
    PreparedDcqlQuery Query,
    KeyId DecryptionKeyId,
    KeyId SigningKeyId,
    IReadOnlyList<string> AllowedEncAlgorithms,
    DateTimeOffset ReceivedAt): OAuthFlowInput;
