namespace Verifiable.Tpm.Structures.Spec.Constants;

/// <summary>
/// TPM_CONSTANTS32 constants (Table 9).
/// </summary>
/// <remarks>
/// <para>
/// Specification:
/// <see href="https://trustedcomputinggroup.org/resource/tpm-library-specification/">TPM 2.0 Library Specification</see>
/// (Part 2: Structures, section "6 Constants", Table 9).
/// </para>
/// </remarks>
public static class TpmConstants32
{
    /// <summary>
    /// ‘TCG’ (FF 54 43 47) value used to differentiate TPM-generated structures from non-TPM structures
    /// </summary>
    public const uint TPM_GENERATED_VALUE = 0xff544347;

    /// <summary>
    /// the maximum number of bits that may be generated by an instantiation of the deterministic pseudo-random bit generator
    /// </summary>
    public const uint TPM_MAX_DERIVATION_BITS = 8192;
}