using System.Diagnostics;

namespace Verifiable.OAuth.Server;

/// <summary>
/// Well-known context bag key constants for Authorization Server request processing.
/// </summary>
/// <remarks>
/// <para>
/// The ASP.NET skin places these values into the context bag before calling
/// <see cref="AuthorizationServer.HandleAsync"/>. The endpoint delegates read
/// them via the typed accessors on <see cref="RequestContextExtensions"/>.
/// </para>
/// <para>
/// The context bag is typed as <c>IReadOnlyDictionary&lt;string, object&gt;</c> to
/// avoid coupling the library to ASP.NET or any other HTTP framework.
/// </para>
/// </remarks>
[DebuggerDisplay("AuthorizationServerHandlers")]
public static class AuthorizationServerHandlers
{
    /// <summary>
    /// Context bag key for the resolved <see cref="Verifiable.OAuth.TenantId"/>.
    /// Set either by the application skin before dispatching, or by the dispatcher
    /// after invoking <see cref="AuthorizationServerOptions.ExtractTenantIdAsync"/>.
    /// Value type: <see cref="Verifiable.OAuth.TenantId"/>.
    /// </summary>
    public const string TenantIdKey = "server.tenantId";

    /// <summary>
    /// Context bag key for the server issuer URI.
    /// Value type: <see cref="Uri"/>.
    /// </summary>
    public const string IssuerKey = "server.issuer";

    /// <summary>
    /// Context bag key for the authenticated subject identifier.
    /// Value type: <see cref="string"/>.
    /// Set by the application's authentication middleware before dispatching to
    /// the authorize endpoint.
    /// </summary>
    public const string SubjectIdKey = "server.subjectId";

    /// <summary>
    /// Context bag key for the authentication time.
    /// Value type: <see cref="DateTimeOffset"/>.
    /// </summary>
    public const string AuthTimeKey = "server.authTime";

    /// <summary>
    /// Context bag key for the <see cref="ClientRegistration"/> resolved at the start
    /// of each request. Set by the dispatcher so <c>BuildInputAsync</c> delegates can
    /// read per-registration values without capturing from outside static lambdas.
    /// Value type: <see cref="ClientRegistration"/>.
    /// </summary>
    public const string RegistrationKey = "server.registration";

    /// <summary>
    /// Context bag key for the flow identifier. Set by <see cref="BuildInputDelegate"/>
    /// implementations on continuing-flow endpoints so the dispatcher can load the
    /// correct state from the store.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public const string FlowIdKey = "server.flowId";

    /// <summary>
    /// Context bag output key for the correlation key generated by
    /// <see cref="BuildInputDelegate"/> on new-flow endpoints.
    /// The dispatcher reads this after <c>BuildInputAsync</c> runs on new flows
    /// to determine the storage key for <see cref="SaveServerFlowStateDelegate"/>.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public const string CorrelationKeyOutputKey = "server.correlationKey";


#pragma warning disable RS0030 // Do not use banned APIs
    /// <summary>
    /// Context bag key for the UTC instant at which effectful verification completed.
    /// Set by the dispatcher before executing the <see cref="OAuthActionExecutor"/>
    /// so action handlers can timestamp results without calling
    /// <see cref="System.DateTimeOffset.UtcNow"/> directly.
    /// Value type: <see cref="System.DateTimeOffset"/>.
    /// </summary>
    public const string VerifiedAtKey = "server.verifiedAt";

    /// <summary>
    /// Context key for accumulated validation results produced during request processing.
    /// Value type: <see cref="System.Collections.Generic.List{T}"/> of
    /// <see cref="Verifiable.Core.Assessment.ClaimIssueResult"/>.
    /// </summary>
    public const string ValidationResultsKey = "server.validationResults";
#pragma warning restore RS0030 // Do not use banned APIs

    /// <summary>
    /// Context-bag key for the <see cref="IssuedTokenSet"/> assembled by the
    /// token endpoint's <c>BuildInputAsync</c> for consumption by
    /// <c>BuildResponse</c>.
    /// </summary>
    /// <remarks>
    /// Token strings are transient — they live on the context bag for the
    /// duration of a single request. The PDA state and persisted flow record
    /// carry only audit metadata (jti, signing key id, issued-at, expires-at)
    /// keyed by token-type response field name.
    /// </remarks>
    public const string IssuedTokensKey = "server.issuedTokens";
}
