using System.Diagnostics;

namespace Verifiable.OAuth.Server;

/// <summary>
/// Well-known context bag key constants for OID4VP verifier request processing.
/// </summary>
/// <remarks>
/// <para>
/// The ASP.NET skin places input values into the context bag before calling
/// <see cref="AuthorizationServerDispatcher.DispatchAsync"/>. The dispatcher and
/// endpoint delegates place output values back into the context bag so the ASP.NET
/// skin can read them after dispatch completes.
/// </para>
/// <para>
/// The flow identifier and <c>request_uri</c> are generated by the server at PAR
/// time — the application does not supply them. The application reads the generated
/// flow identifier back from the context bag via <see cref="GeneratedFlowId"/> after
/// the PAR dispatch call returns, and uses it to construct the QR code or deep link.
/// </para>
/// </remarks>
[DebuggerDisplay("Oid4VpContextKeys")]
public static class Oid4VpContextKeys
{
    //Input keys — set by the application before dispatching.

    /// <summary>
    /// The base URI of the server, used to construct the <c>request_uri</c>.
    /// The PAR endpoint appends <c>/{segment}/request/{flowId}</c> to produce the full URI.
    /// Value type: <see cref="Uri"/>.
    /// Example: <c>https://verifier.example.com</c>.
    /// </summary>
    public const string RequestUriBase = "oid4vp.requestUriBase";

    /// <summary>
    /// The prepared DCQL query describing the credentials the Verifier requires.
    /// Value type: <see cref="Verifiable.Core.Dcql.PreparedDcqlQuery"/>.
    /// </summary>
    public const string PreparedQuery = "oid4vp.preparedQuery";

    /// <summary>
    /// The transaction nonce bound into the JAR and echoed in the VP token.
    /// Value type: <see cref="TransactionNonce"/>.
    /// </summary>
    public const string TransactionNonce = "oid4vp.transactionNonce";

    /// <summary>
    /// The identifier of the decryption key the Verifier will use to decrypt the
    /// Wallet's Authorization Response JWE. The corresponding public key is published
    /// in <c>client_metadata.jwks</c> inside the JAR.
    /// Value type: <see cref="Verifiable.Cryptography.KeyId"/>.
    /// </summary>
    public const string DecryptionKeyId = "oid4vp.decryptionKeyId";

    /// <summary>
    /// The <c>redirect_uri</c> returned to the Wallet in the direct_post HTTP 200
    /// response body for same-device flows per
    /// <see href="https://openid.net/specs/openid-4-verifiable-presentations-1_0.html">OID4VP 1.0 §8.2</see>.
    /// Value type: <see cref="Uri"/> or absent for cross-device flows.
    /// Set by the application before dispatching the direct_post call.
    /// </summary>
    public const string RedirectUri = "oid4vp.redirectUri";


    //Output keys — set by the endpoint delegates, read by the application after dispatch.

    /// <summary>
    /// The flow identifier generated by the PAR endpoint.
    /// Value type: <see cref="string"/>.
    /// Read by the application after PAR dispatch to construct the QR code or deep link.
    /// </summary>
    public const string GeneratedFlowId = "oid4vp.generatedFlowId";

    /// <summary>
    /// The full <c>request_uri</c> generated by the PAR endpoint.
    /// Value type: <see cref="Uri"/>.
    /// Read by the application after PAR dispatch to encode into the QR code or deep link.
    /// </summary>
    public const string GeneratedRequestUri = "oid4vp.generatedRequestUri";

    /// <summary>
    /// The compact JWS JAR produced by the JAR request endpoint.
    /// Value type: <see cref="string"/>.
    /// Read by the application after JAR dispatch to write into the HTTP response body.
    /// </summary>
    public const string CompactJar = "oid4vp.compactJar";
}
