using System.Buffers;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Verifiable.OAuth;

/// <summary>
/// An ephemeral ECDH key pair generated by the verifier for encrypting one authorization response.
/// </summary>
/// <remarks>
/// <para>
/// HAIP 1.0 requires the authorization response to be encrypted using ECDH-ES key agreement
/// as defined in
/// <see href="https://www.rfc-editor.org/rfc/rfc7518#section-4.6">RFC 7518 §4.6</see>,
/// with P-256 and either A128GCM or A256GCM as the content encryption algorithm.
/// </para>
/// <para>
/// The public key is embedded in the JAR as <c>client_metadata.jwks</c> so the
/// authorization response sender can encrypt its direct_post.jwt to it. The private key
/// is held in the flow state and used once to decrypt that response. Both components
/// must be discarded after decryption completes.
/// </para>
/// <para>
/// This type owns the private key bytes and must be disposed when the flow state that
/// holds it is superseded or abandoned.
/// </para>
/// </remarks>
[DebuggerDisplay("EphemeralEncryptionKeyPair PublicKeyLength={PublicKeyJwk.Length}")]
public sealed class EphemeralEncryptionKeyPair : IDisposable, IEquatable<EphemeralEncryptionKeyPair>
{
    private bool disposed;
    private readonly IMemoryOwner<byte> privateKeyOwner;

    /// <summary>
    /// The P-256 public key serialized as a JWK JSON string. Included in the signed JAR
    /// as <c>client_metadata.jwks</c>. Safe to transmit.
    /// </summary>
    public string PublicKeyJwk { get; }

    /// <summary>
    /// The raw private scalar bytes. Valid only while this instance has not been disposed.
    /// Never transmitted.
    /// </summary>
    public ReadOnlyMemory<byte> PrivateKeyBytes => privateKeyOwner.Memory;


    /// <summary>
    /// Initializes an <see cref="EphemeralEncryptionKeyPair"/> taking ownership of the private key memory.
    /// </summary>
    /// <param name="publicKeyJwk">
    /// The P-256 public key as a JWK JSON string. Must not be null or empty.
    /// </param>
    /// <param name="privateKeyOwner">
    /// Memory owner for the raw private scalar bytes. Ownership transfers to this instance.
    /// </param>
    public EphemeralEncryptionKeyPair(string publicKeyJwk, IMemoryOwner<byte> privateKeyOwner)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(publicKeyJwk);
        ArgumentNullException.ThrowIfNull(privateKeyOwner);

        PublicKeyJwk = publicKeyJwk;
        this.privateKeyOwner = privateKeyOwner;
    }


    /// <inheritdoc/>
    public void Dispose()
    {
        if(!disposed)
        {
            privateKeyOwner.Dispose();
            disposed = true;
        }
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public bool Equals(EphemeralEncryptionKeyPair? other)
    {
        if(other is null)
        {
            return false;
        }

        if(ReferenceEquals(this, other))
        {
            return true;
        }

        return PublicKeyJwk == other.PublicKeyJwk
            && PrivateKeyBytes.Span.SequenceEqual(other.PrivateKeyBytes.Span);
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override bool Equals([NotNullWhen(true)] object? obj) =>
        obj is EphemeralEncryptionKeyPair other && Equals(other);


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(PublicKeyJwk);
        hash.AddBytes(PrivateKeyBytes.Span);
        return hash.ToHashCode();
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator ==(EphemeralEncryptionKeyPair? left, EphemeralEncryptionKeyPair? right) =>
        left is null ? right is null : left.Equals(right);


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator !=(EphemeralEncryptionKeyPair? left, EphemeralEncryptionKeyPair? right) =>
        !(left == right);
}
