using System.Buffers;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Verifiable.Cryptography;
using Verifiable.JCose;

namespace Verifiable.OAuth;

/// <summary>
/// An ephemeral ECDH key pair generated by the Verifier for encrypting one authorization
/// response. The public key is embedded in the JAR as <c>client_metadata.jwks</c> so the
/// authorization response sender can encrypt its <c>direct_post.jwt</c> to it. The private
/// key is held in the flow state and used once to decrypt that response.
/// </summary>
/// <remarks>
/// <para>
/// HAIP 1.0 requires the authorization response to be encrypted using ECDH-ES key agreement
/// as defined in
/// <see href="https://www.rfc-editor.org/rfc/rfc7518#section-4.6">RFC 7518 §4.6</see>,
/// with P-256 and either A128GCM or A256GCM as the content encryption algorithm.
/// </para>
/// <para>
/// This type owns the private key bytes and must be disposed when the flow state that
/// holds it is superseded or abandoned.
/// </para>
/// </remarks>
[DebuggerDisplay("EphemeralEncryptionKeyPair PublicKeyJwk.Length={PublicKeyJwk.Length}")]
public sealed class EphemeralEncryptionKeyPair: IDisposable, IEquatable<EphemeralEncryptionKeyPair>
{
    private bool disposed;
    private readonly IMemoryOwner<byte> privateKeyOwner;

    /// <summary>
    /// The P-256 public key serialized as a JWKS JSON string carrying a single JWK with
    /// <c>use=enc</c>. Embedded in the signed JAR as <c>client_metadata.jwks</c>.
    /// Safe to transmit.
    /// </summary>
    public string PublicKeyJwk { get; }

    /// <summary>
    /// The raw private scalar bytes. Valid only while this instance has not been disposed.
    /// Never transmitted.
    /// </summary>
    public ReadOnlyMemory<byte> PrivateKeyBytes => privateKeyOwner.Memory;


    /// <summary>
    /// Initializes an <see cref="EphemeralEncryptionKeyPair"/> taking ownership of the
    /// private key memory.
    /// </summary>
    /// <param name="publicKeyJwk">
    /// The P-256 public key as a JWKS JSON string. Must not be null or empty.
    /// </param>
    /// <param name="privateKeyOwner">
    /// Memory owner for the raw private scalar bytes. Ownership transfers to this instance.
    /// </param>
    public EphemeralEncryptionKeyPair(string publicKeyJwk, IMemoryOwner<byte> privateKeyOwner)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(publicKeyJwk);
        ArgumentNullException.ThrowIfNull(privateKeyOwner);

        PublicKeyJwk = publicKeyJwk;
        this.privateKeyOwner = privateKeyOwner;
    }


    /// <summary>
    /// Creates an <see cref="EphemeralEncryptionKeyPair"/> from a P-256 exchange key pair.
    /// The public key is serialised to a JWKS JSON string using <see cref="JwkJsonWriter"/>
    /// without depending on a JSON serialisation library.
    /// </summary>
    /// <param name="publicKey">
    /// The P-256 exchange public key in uncompressed encoding: <c>0x04 || X || Y</c>.
    /// Tagged with <see cref="CryptoTags.P256ExchangePublicKey"/>.
    /// </param>
    /// <param name="privateKey">
    /// The P-256 exchange private key scalar. Tagged with
    /// <see cref="CryptoTags.P256ExchangePrivateKey"/>. Ownership transfers to the returned
    /// instance.
    /// </param>
    /// <param name="base64UrlEncoder">Delegate for Base64url encoding.</param>
    /// <param name="pool">Memory pool for intermediate allocations.</param>
    /// <returns>
    /// A new <see cref="EphemeralEncryptionKeyPair"/>. The caller owns and must dispose it.
    /// </returns>
    public static EphemeralEncryptionKeyPair CreateForP256(
        PublicKeyMemory publicKey,
        IMemoryOwner<byte> privateKeyOwner,
        EncodeDelegate base64UrlEncoder,
        MemoryPool<byte> pool)
    {
        ArgumentNullException.ThrowIfNull(publicKey);
        ArgumentNullException.ThrowIfNull(privateKeyOwner);
        ArgumentNullException.ThrowIfNull(base64UrlEncoder);
        ArgumentNullException.ThrowIfNull(pool);

        string jwksJson = BuildP256JwksJson(publicKey, base64UrlEncoder, pool);
        return new EphemeralEncryptionKeyPair(jwksJson, privateKeyOwner);
    }


    /// <summary>
    /// Serialises a P-256 exchange public key to a JWKS JSON string with <c>use=enc</c>,
    /// without wrapping the private key. Use when the private key is managed separately,
    /// for example stored in a key store indexed by <c>KeyId</c>.
    /// </summary>
    /// <param name="publicKey">
    /// The P-256 exchange public key in uncompressed encoding: <c>0x04 || X || Y</c>.
    /// </param>
    /// <param name="base64UrlEncoder">Delegate for Base64url encoding.</param>
    /// <param name="pool">Memory pool for intermediate allocations.</param>
    /// <returns>
    /// A JWKS JSON string: <c>{"keys":[{"crv":"P-256","kty":"EC","use":"enc","x":"...","y":"..."}]}</c>.
    /// </returns>
    public static string CreatePublicKeyJwks(
        PublicKeyMemory publicKey,
        EncodeDelegate base64UrlEncoder,
        MemoryPool<byte> pool)
    {
        ArgumentNullException.ThrowIfNull(publicKey);
        ArgumentNullException.ThrowIfNull(base64UrlEncoder);
        ArgumentNullException.ThrowIfNull(pool);

        return BuildP256JwksJson(publicKey, base64UrlEncoder, pool);
    }


    private static string BuildP256JwksJson(
        PublicKeyMemory publicKey,
        EncodeDelegate base64UrlEncoder,
        MemoryPool<byte> pool)
    {
        //Uncompressed P-256 point: 0x04 || X (32 bytes) || Y (32 bytes) = 65 bytes.
        ReadOnlySpan<byte> point = publicKey.AsReadOnlySpan();
        const int coordinateLength = 32;
        const int uncompressedPointLength = 1 + coordinateLength * 2;

        if(point.Length != uncompressedPointLength || point[0] != 0x04)
        {
            throw new ArgumentException(
                "P-256 exchange public key must be in uncompressed encoding (0x04 || X || Y, 65 bytes).",
                nameof(publicKey));
        }

        string xEncoded = base64UrlEncoder(point.Slice(1, coordinateLength));
        string yEncoded = base64UrlEncoder(point.Slice(1 + coordinateLength, coordinateLength));

        //Build JWKS JSON: {"keys":[{"crv":"P-256","kty":"EC","use":"enc","x":"...","y":"..."}]}
        int bufferLength =
            JwkTemplateConstants.JwksArrayOverhead +
            JwkTemplateConstants.EcTemplateOverhead +
            JwkTemplateConstants.UseEncOverhead +
            Encoding.UTF8.GetByteCount(WellKnownCurveValues.P256) +
            Encoding.UTF8.GetByteCount(WellKnownKeyTypeValues.Ec) +
            Encoding.UTF8.GetByteCount(xEncoded) +
            Encoding.UTF8.GetByteCount(yEncoded);

        using IMemoryOwner<byte> bufferOwner = pool.Rent(bufferLength);
        JwkJsonWriter writer = new(bufferOwner.Memory.Span);

        writer.WriteObjectStart();
        writer.WritePropertyRaw("keys", "[");
        writer.WriteObjectStart();
        writer.WriteProperty("crv", WellKnownCurveValues.P256);
        writer.WritePropertySeparator();
        writer.WriteProperty("kty", WellKnownKeyTypeValues.Ec);
        writer.WritePropertySeparator();
        writer.WriteProperty("use", "enc");
        writer.WritePropertySeparator();
        writer.WriteProperty("x", xEncoded);
        writer.WritePropertySeparator();
        writer.WriteProperty("y", yEncoded);
        writer.WriteObjectEnd();
        writer.WriteArrayEnd();
        writer.WriteObjectEnd();

        return Encoding.UTF8.GetString(bufferOwner.Memory.Span[..writer.Position]);
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        if(!disposed)
        {
            privateKeyOwner.Dispose();
            disposed = true;
        }
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public bool Equals(EphemeralEncryptionKeyPair? other)
    {
        if(other is null)
        {
            return false;
        }

        if(ReferenceEquals(this, other))
        {
            return true;
        }

        return PublicKeyJwk == other.PublicKeyJwk
            && PrivateKeyBytes.Span.SequenceEqual(other.PrivateKeyBytes.Span);
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override bool Equals([NotNullWhen(true)] object? obj) =>
        obj is EphemeralEncryptionKeyPair other && Equals(other);


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(PublicKeyJwk);
        hash.AddBytes(PrivateKeyBytes.Span);
        return hash.ToHashCode();
    }


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator ==(EphemeralEncryptionKeyPair? left, EphemeralEncryptionKeyPair? right) =>
        left is null ? right is null : left.Equals(right);


    /// <inheritdoc/>
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static bool operator !=(EphemeralEncryptionKeyPair? left, EphemeralEncryptionKeyPair? right) =>
        !(left == right);
}
