using System;
using System.Buffers;
using System.Diagnostics;

namespace Verifiable.Cryptography.Secdsa;

/// <summary>
/// Represents the encrypted and signed instruction produced by the wallet
/// and sent to the WSCA (Algorithm 36 of the SECDSA specification at
/// https://wellet.nl/SECDSA-EUDI-wallet-latest.pdf).
/// </summary>
/// <remarks>
/// <para>
/// The instruction bundles:
/// </para>
/// <list type="bullet">
///   <item><description>A Schnorr challenge Chal(SN) signed with the NCH private key u (Algorithm 21).</description></item>
///   <item><description>The encrypted payload ciphertext C and authentication tag T.</description></item>
///   <item><description>The SECDSA nonce point R (full format, uncompressed).</description></item>
///   <item><description>The ECDH verification point R' = aU·R (uncompressed), valid when the correct PIN was used.</description></item>
///   <item><description>The outer sequence number for early replay detection.</description></item>
/// </list>
/// </remarks>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class BlindedSecdsaInstruction: IDisposable
{
    private bool Disposed { get; set; }

    private IMemoryOwner<byte> ChallengeOwner { get; }

    private IMemoryOwner<byte> CiphertextOwner { get; }

    private IMemoryOwner<byte> TagOwner { get; }

    /// <summary>
    /// Gets the outer sequence number for early replay detection.
    /// </summary>
    public ulong SequenceNumber { get; }

    /// <summary>
    /// Gets the Schnorr challenge Chal(SN) generated by Algorithm 21.
    /// </summary>
    public ReadOnlyMemory<byte> Challenge { get; }

    /// <summary>
    /// Gets the SECDSA nonce point R in uncompressed form.
    /// </summary>
    public EcPointBytes NoncePoint { get; }

    /// <summary>
    /// Gets the ECDH verification point R' in uncompressed form.
    /// </summary>
    public EcPointBytes VerificationPoint { get; }

    /// <summary>
    /// Gets the authenticated encryption ciphertext C.
    /// </summary>
    public ReadOnlyMemory<byte> Ciphertext { get; }

    /// <summary>
    /// Gets the AES-GCM authentication tag T.
    /// </summary>
    public ReadOnlyMemory<byte> AuthenticationTag { get; }

    /// <summary>
    /// Creates a <see cref="BlindedSecdsaInstruction"/> from its component parts.
    /// </summary>
    /// <param name="sequenceNumber">The outer sequence number.</param>
    /// <param name="challengeBytes">The serialized Schnorr challenge.</param>
    /// <param name="noncePoint">The SECDSA nonce point R. Ownership transfers to this instance.</param>
    /// <param name="verificationPoint">The verification point R'. Ownership transfers to this instance.</param>
    /// <param name="ciphertextBytes">The encrypted payload bytes.</param>
    /// <param name="authTagBytes">The AES-GCM authentication tag.</param>
    /// <param name="pool">The memory pool for buffer allocation.</param>
    /// <returns>A new <see cref="BlindedSecdsaInstruction"/>.</returns>
    public static BlindedSecdsaInstruction Create(
        ulong sequenceNumber,
        ReadOnlySpan<byte> challengeBytes,
        EcPointBytes noncePoint,
        EcPointBytes verificationPoint,
        ReadOnlySpan<byte> ciphertextBytes,
        ReadOnlySpan<byte> authTagBytes,
        MemoryPool<byte> pool)
    {
        ArgumentNullException.ThrowIfNull(noncePoint);
        ArgumentNullException.ThrowIfNull(verificationPoint);
        ArgumentNullException.ThrowIfNull(pool);

        IMemoryOwner<byte> challengeOwner = pool.Rent(challengeBytes.Length);
        challengeBytes.CopyTo(challengeOwner.Memory.Span);

        IMemoryOwner<byte> ciphertextOwner = pool.Rent(ciphertextBytes.Length);
        ciphertextBytes.CopyTo(ciphertextOwner.Memory.Span);

        IMemoryOwner<byte> tagOwner = pool.Rent(authTagBytes.Length);
        authTagBytes.CopyTo(tagOwner.Memory.Span);

        return new BlindedSecdsaInstruction(
            sequenceNumber,
            challengeOwner,
            challengeOwner.Memory.Slice(0, challengeBytes.Length),
            noncePoint,
            verificationPoint,
            ciphertextOwner,
            ciphertextOwner.Memory.Slice(0, ciphertextBytes.Length),
            tagOwner,
            tagOwner.Memory.Slice(0, authTagBytes.Length));
    }

    private BlindedSecdsaInstruction(
        ulong sequenceNumber,
        IMemoryOwner<byte> challengeOwner,
        ReadOnlyMemory<byte> challenge,
        EcPointBytes noncePoint,
        EcPointBytes verificationPoint,
        IMemoryOwner<byte> ciphertextOwner,
        ReadOnlyMemory<byte> ciphertext,
        IMemoryOwner<byte> tagOwner,
        ReadOnlyMemory<byte> authenticationTag)
    {
        SequenceNumber = sequenceNumber;
        ChallengeOwner = challengeOwner;
        Challenge = challenge;
        NoncePoint = noncePoint;
        VerificationPoint = verificationPoint;
        CiphertextOwner = ciphertextOwner;
        Ciphertext = ciphertext;
        TagOwner = tagOwner;
        AuthenticationTag = authenticationTag;
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        if(!Disposed)
        {
            ChallengeOwner.Dispose();
            NoncePoint.Dispose();
            VerificationPoint.Dispose();
            CiphertextOwner.Dispose();
            TagOwner.Dispose();
            Disposed = true;
        }
    }

    private string DebuggerDisplay =>
        $"BlindedSecdsaInstruction(SN={SequenceNumber}, Ciphertext={Ciphertext.Length} bytes, Tag={AuthenticationTag.Length} bytes)";
}