using System.Buffers;
using System.Diagnostics;

namespace Verifiable.Cryptography.Secdsa;

/// <summary>
/// Represents the encrypted and signed instruction produced by the wallet
/// and sent to the Wallet Secure Cryptographic Application (WSCA)
/// (Algorithm 36 of the SECDSA specification).
/// </summary>
/// <remarks>
/// <para>
/// The instruction bundles:
/// </para>
/// <list type="bullet">
///   <item><description>A Schnorr challenge Chal(SN) signed with the Native Cryptographic
///   Hardware (NCH) private key u (Algorithm 21).</description></item>
///   <item><description>The encrypted payload ciphertext C and AES-GCM authentication tag T.
///   The payload contains the instruction, the scaled verification values G'' and Y'',
///   the Schnorr ZKP, and any additional authorisation data. The sequence number SN
///   serves as AES-GCM additional authenticated data (AAD), binding the plaintext
///   sequence number to the ciphertext.</description></item>
///   <item><description>The SECDSA nonce point R (full format, uncompressed).</description></item>
///   <item><description>The ECDH verification point R' = aU·R (uncompressed), valid when
///   the correct PIN was used.</description></item>
///   <item><description>The outer sequence number for early replay detection.</description></item>
/// </list>
/// <para>
/// Not yet implemented (fields are populated with placeholder bytes in current tests):
/// </para>
/// <list type="bullet">
///   <item><description>Algorithm 21: Schnorr challenge generation signed with the NCH
///   private key u. See <see cref="Challenge"/>.</description></item>
///   <item><description>HKDF key derivation from R': the symmetric key K is derived from
///   the x-coordinate of R' before AES-GCM encryption. Neither step is implemented.
///   See <see cref="Ciphertext"/> and <see cref="AuthenticationTag"/>.</description></item>
///   <item><description>PIN-binder key derivation (Annex B Algorithms 24/25/27): the
///   PIN-key scalar P is derived from the user's PIN and a Native Cryptographic Hardware
///   (NCH)-bound binder key KP. In the current tests P is modelled as a random scalar.
///   </description></item>
/// </list>
/// <para>
/// When the correct PIN was used, the WSCA's AES-GCM decryption succeeds and the
/// authentication tag verifies. When the wrong PIN was used, K is wrong and the
/// AES-GCM authentication tag verification fails. This is the sole PIN verification
/// step -- no PIN value is ever compared against a stored reference.
/// See <see href="https://github.com/Lumoin/Verifiable/issues/529"/>.
/// </para>
/// </remarks>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class BlindedSecdsaInstruction: IDisposable
{
    /// <summary>Tracks whether this instance has been disposed.</summary>
    private bool Disposed { get; set; }

    /// <summary>Owns the memory backing <see cref="Challenge"/>.</summary>
    private IMemoryOwner<byte> ChallengeOwner { get; }

    /// <summary>Owns the memory backing <see cref="Ciphertext"/>.</summary>
    private IMemoryOwner<byte> CiphertextOwner { get; }

    /// <summary>Owns the memory backing <see cref="AuthenticationTag"/>.</summary>
    private IMemoryOwner<byte> TagOwner { get; }

    /// <summary>
    /// Gets the outer sequence number for early replay detection.
    /// </summary>
    public ulong SequenceNumber { get; }

    /// <summary>
    /// Gets the Schnorr challenge Chal(SN) generated by Algorithm 21.
    /// </summary>
    /// <remarks>
    /// Not yet implemented: Algorithm 21 requires a Schnorr challenge signed with
    /// the Native Cryptographic Hardware (NCH) private key u, binding the instruction
    /// to the specific NCH key so the Wallet Secure Cryptographic Application (WSCA)
    /// perimeter can verify the instruction is genuine before it reaches the WSCA.
    /// In the current implementation this field is populated with placeholder bytes.
    /// </remarks>
    public ReadOnlyMemory<byte> Challenge { get; }

    /// <summary>
    /// Gets the SECDSA nonce point R in uncompressed form.
    /// </summary>
    public EcPointBytes NoncePoint { get; }

    /// <summary>
    /// Gets the ECDH verification point R' in uncompressed form.
    /// </summary>
    public EcPointBytes VerificationPoint { get; }

    /// <summary>
    /// Gets the authenticated encryption ciphertext C.
    /// </summary>
    /// <remarks>
    /// Not yet implemented: the ciphertext is produced by AES-GCM encryption of the
    /// instruction payload (instruction text, G'', Y'', ZKP, and additional data) under
    /// a key K derived from R' via HKDF. Neither the HKDF key derivation from R' nor
    /// the AES-GCM encryption step is implemented. In the current tests this field
    /// is populated with placeholder bytes. The encryption and key derivation must be
    /// provided via delegates following the same pluggable pattern used for NCH and
    /// Wallet Secure Cryptographic Device (WSCD) operations elsewhere in this library.
    /// </remarks>
    public ReadOnlyMemory<byte> Ciphertext { get; }

    /// <summary>
    /// Gets the AES-GCM authentication tag T.
    /// </summary>
    /// <remarks>
    /// Not yet implemented: paired with <see cref="Ciphertext"/>. The sequence number
    /// <see cref="SequenceNumber"/> serves as AES-GCM additional authenticated data
    /// (AAD), binding the plaintext sequence number to the ciphertext. When the WSCA
    /// decrypts and the authentication tag verification fails, that constitutes the
    /// sole PIN verification step -- no PIN value is ever compared against a stored
    /// reference. In the current tests this field is populated with placeholder bytes.
    /// </remarks>
    public ReadOnlyMemory<byte> AuthenticationTag { get; }

    /// <summary>
    /// Creates a <see cref="BlindedSecdsaInstruction"/> from its component parts.
    /// </summary>
    /// <param name="sequenceNumber">The outer sequence number.</param>
    /// <param name="challengeBytes">The serialized Schnorr challenge.</param>
    /// <param name="noncePoint">The SECDSA nonce point R. Ownership transfers to this instance.</param>
    /// <param name="verificationPoint">The verification point R'. Ownership transfers to this instance.</param>
    /// <param name="ciphertextBytes">The encrypted payload bytes.</param>
    /// <param name="authTagBytes">The AES-GCM authentication tag.</param>
    /// <param name="pool">The memory pool for buffer allocation.</param>
    /// <returns>A new <see cref="BlindedSecdsaInstruction"/>.</returns>
    public static BlindedSecdsaInstruction Create(
        ulong sequenceNumber,
        ReadOnlySpan<byte> challengeBytes,
        EcPointBytes noncePoint,
        EcPointBytes verificationPoint,
        ReadOnlySpan<byte> ciphertextBytes,
        ReadOnlySpan<byte> authTagBytes,
        MemoryPool<byte> pool)
    {
        ArgumentNullException.ThrowIfNull(noncePoint);
        ArgumentNullException.ThrowIfNull(verificationPoint);
        ArgumentNullException.ThrowIfNull(pool);

        IMemoryOwner<byte> challengeOwner = pool.Rent(challengeBytes.Length);
        challengeBytes.CopyTo(challengeOwner.Memory.Span);

        IMemoryOwner<byte> ciphertextOwner = pool.Rent(ciphertextBytes.Length);
        ciphertextBytes.CopyTo(ciphertextOwner.Memory.Span);

        IMemoryOwner<byte> tagOwner = pool.Rent(authTagBytes.Length);
        authTagBytes.CopyTo(tagOwner.Memory.Span);

        return new BlindedSecdsaInstruction(
            sequenceNumber,
            challengeOwner,
            challengeOwner.Memory.Slice(0, challengeBytes.Length),
            noncePoint,
            verificationPoint,
            ciphertextOwner,
            ciphertextOwner.Memory.Slice(0, ciphertextBytes.Length),
            tagOwner,
            tagOwner.Memory.Slice(0, authTagBytes.Length));
    }

    private BlindedSecdsaInstruction(
        ulong sequenceNumber,
        IMemoryOwner<byte> challengeOwner,
        ReadOnlyMemory<byte> challenge,
        EcPointBytes noncePoint,
        EcPointBytes verificationPoint,
        IMemoryOwner<byte> ciphertextOwner,
        ReadOnlyMemory<byte> ciphertext,
        IMemoryOwner<byte> tagOwner,
        ReadOnlyMemory<byte> authenticationTag)
    {
        SequenceNumber = sequenceNumber;
        ChallengeOwner = challengeOwner;
        Challenge = challenge;
        NoncePoint = noncePoint;
        VerificationPoint = verificationPoint;
        CiphertextOwner = ciphertextOwner;
        Ciphertext = ciphertext;
        TagOwner = tagOwner;
        AuthenticationTag = authenticationTag;
    }


    /// <inheritdoc/>
    public void Dispose()
    {
        if(!Disposed)
        {
            ChallengeOwner.Dispose();
            NoncePoint.Dispose();
            VerificationPoint.Dispose();
            CiphertextOwner.Dispose();
            TagOwner.Dispose();
            Disposed = true;
        }
    }


    private string DebuggerDisplay =>
        $"BlindedSecdsaInstruction(SN={SequenceNumber}, Ciphertext={Ciphertext.Length} bytes, Tag={AuthenticationTag.Length} bytes)";
}
