using System.Buffers;
using System.Diagnostics;

namespace Verifiable.Cryptography.Secdsa;

/// <summary>
/// Holds a Schnorr zero-knowledge proof as (r, s) scalar pair in wire-level byte form.
/// </summary>
/// <remarks>
/// <para>
/// Generated by Algorithm 19 and verified by Algorithm 20 of the SECDSA specification.
/// The r and s values are big-endian integers of
/// <see cref="EllipticCurveConstants.P256.PointArrayLength"/> bytes each for P-256.
/// This type owns its memory and must be disposed.
/// </para>
/// </remarks>
[DebuggerDisplay("{DebuggerDisplay,nq}")]
public sealed class SchnorrProofBytes: IDisposable
{
    /// <summary>Tracks whether this instance has been disposed.</summary>
    private bool Disposed { get; set; }

    /// <summary>Owns the contiguous buffer holding r followed by s.</summary>
    private IMemoryOwner<byte> Owner { get; }

    /// <summary>Byte length of the r component (Fiat-Shamir challenge hash) within <see cref="Owner"/>.</summary>
    private int RLength { get; }

    /// <summary>Byte length of the s component (Schnorr response scalar) within <see cref="Owner"/>.</summary>
    private int SLength { get; }

    /// <summary>
    /// Gets the r component of the proof — the Fiat-Shamir challenge hash.
    /// </summary>
    public ReadOnlyMemory<byte> R => Owner.Memory.Slice(0, RLength);

    /// <summary>
    /// Gets the s component of the proof — the Schnorr response scalar.
    /// </summary>
    public ReadOnlyMemory<byte> S => Owner.Memory.Slice(RLength, SLength);


    /// <summary>
    /// Creates a Schnorr proof from r and s byte spans.
    /// </summary>
    /// <param name="r">The Fiat-Shamir challenge hash bytes.</param>
    /// <param name="s">The Schnorr response scalar bytes.</param>
    /// <param name="pool">The memory pool to allocate from.</param>
    /// <returns>A new <see cref="SchnorrProofBytes"/> owning a contiguous buffer.</returns>
    public static SchnorrProofBytes Create(
        ReadOnlySpan<byte> r,
        ReadOnlySpan<byte> s,
        MemoryPool<byte> pool)
    {
        ArgumentNullException.ThrowIfNull(pool);
        IMemoryOwner<byte> owner = pool.Rent(r.Length + s.Length);
        r.CopyTo(owner.Memory.Span);
        s.CopyTo(owner.Memory.Span.Slice(r.Length));

        return new SchnorrProofBytes(owner, r.Length, s.Length);
    }


    /// <inheritdoc/>
    public void Dispose()
    {
        if(!Disposed)
        {
            Owner.Dispose();
            Disposed = true;
        }
    }


    private SchnorrProofBytes(IMemoryOwner<byte> owner, int rLength, int sLength)
    {
        Owner = owner;
        RLength = rLength;
        SLength = sLength;
    }


    private string DebuggerDisplay => $"SchnorrProofBytes(R={RLength} bytes, S={SLength} bytes)";
}
