using System.Diagnostics;
using System.Numerics;

namespace Verifiable.Cryptography.Secdsa;

/// <summary>
/// Represents a Schnorr zero-knowledge proof as (r, s) scalar pair.
/// </summary>
/// <remarks>
/// Generated by Algorithm 19 and verified by Algorithm 20. Proves knowledge
/// of a scalar d such that Di = d*Gi for all i, without revealing d.
/// </remarks>
/// <param name="R">The Fiat-Shamir challenge hash.</param>
/// <param name="S">The Schnorr response scalar.</param>
[DebuggerDisplay("SchnorrZkProof(R={R}, S={S})")]
public sealed record SchnorrZkProof(BigInteger R, BigInteger S);
