using System.Diagnostics;
using System.Numerics;

namespace Verifiable.Cryptography.Secdsa;

/// <summary>
/// Represents a SECDSA key pair generated by Algorithm 1.
/// </summary>
/// <remarks>
/// <para>
/// The SECDSA key pair consists of:
/// </para>
/// <list type="bullet">
///   <item><description><see cref="PublicKey"/>: Y = P*U = P*u*G, the publicly verifiable SECDSA key.</description></item>
///   <item><description><see cref="NchPrivateKey"/>: u, bound to the NCH (e.g. TPM). Non-exportable in production.</description></item>
///   <item><description><see cref="PinKey"/>: P, derived from the user PIN and a device-bound secret via the PIN-binder construction in Annex B.</description></item>
/// </list>
/// <para>
/// Neither u alone nor P alone can produce a valid signature. The WSCA verifies
/// that both factors were present but cannot itself generate signatures.
/// </para>
/// <para>
/// In production, <see cref="NchPrivateKey"/> is a TPM handle and never exposed
/// as a scalar. This representation is for the software-only Phase 1 implementation.
/// </para>
/// </remarks>
/// <param name="PublicKey">The SECDSA public key Y = P*U.</param>
/// <param name="NchPrivateKey">The NCH-bound private key u.</param>
/// <param name="PinKey">The ephemeral PIN-derived key P.</param>
[DebuggerDisplay("SecdsaKeyPair(Y={PublicKey})")]
public sealed record SecdsaKeyPair(EcPoint PublicKey, BigInteger NchPrivateKey, BigInteger PinKey);