using System.Collections.Immutable;
using Microsoft.Extensions.Time.Testing;
using Verifiable.Core.Dcql;
using Verifiable.OAuth;
using Verifiable.OAuth.Client;
using Verifiable.OAuth.Oid4Vp;
using Verifiable.OAuth.Oid4Vp.States;
using Verifiable.OAuth.Oid4Vp.Wallet;
using Verifiable.OAuth.Oid4Vp.Wallet.States;
using Verifiable.OAuth.Server;
using Verifiable.Tests.TestInfrastructure;

namespace Verifiable.Tests.OAuth;

/// <summary>
/// Full-flow integration test for an SD-CWT (<c>dc+sd-cwt</c>) OID4VP presentation
/// against a pinned-key verifier registration — the SD-CWT counterpart of
/// <see cref="Oid4VpMdocFlowIntegrationTests"/>. Drives the verifier through its
/// real PDA pipeline (PAR → JAR served → encrypted direct_post →
/// PresentationVerified) and the executor's <c>dc+sd-cwt</c> dispatch branch,
/// which runs the holder-binding (Key Binding Token) and issuer verifications
/// through the
/// <see cref="Verifiable.OAuth.Validation.ValidationProfiles.Haip10SdCwtRules"/>
/// ClaimIssuer.
/// </summary>
/// <remarks>
/// The host, verification seams, SD-CWT issuance, DCQL query, presentation
/// drop-out (the Core disclosure engine + KBT signing), and the verified-claims
/// assertion all come from the shared <see cref="SdCwtVpFixture"/>, which the
/// scheme × format matrix (<see cref="Oid4VpSchemeFormatMatrixTests"/>) also
/// drives against every client-id scheme. This test pins the remaining axis the
/// matrix does not: a <see cref="TestHostShell.RegisterClient"/> verifier (the
/// <see cref="PolicyProfile.Oid4VpVerifier"/> registration path) resolved via the
/// pinned-key resolver rather than a client-id scheme. The drop-out selects the
/// minimal set the query asks for (given + family, withholding email), so the
/// assertion also covers withholding. Unlike mdoc, SD-CWT needs no <c>apu</c> /
/// SessionTranscript — the holder binding rides entirely in the KBT. Firewalled:
/// only the compact JAR (in) and compact JWE (out) cross the party boundary.
/// </remarks>
[TestClass]
internal sealed class Oid4VpSdCwtFlowIntegrationTests
{
    /// <summary>The ambient MSTest context, supplying the cancellation token this class's flows run under.</summary>
    public required TestContext TestContext { get; set; }

    /// <summary>The fake time provider driving this test class's clock.</summary>
    private FakeTimeProvider TimeProvider { get; } = new FakeTimeProvider(
        new DateTimeOffset(2026, 5, 26, 12, 0, 0, TimeSpan.Zero));

    /// <summary>The verifier's <c>client_id</c> for the registrations in this class.</summary>
    private const string VerifierClientId = "https://verifier.example.com";

    /// <summary>
    /// <see cref="VerifierClientId"/> as a <see cref="Uri"/>, the shape
    /// <see cref="TestHostShell.RegisterClient"/> requires for verifier registration.
    /// </summary>
    private static Uri VerifierBaseUri { get; } = new("https://verifier.example.com");

    /// <summary>
    /// The capabilities the verifier registration needs to run the OID4VP SD-CWT presentation
    /// pipeline: verifiable presentation, JWKS publication, and discovery metadata.
    /// </summary>
    private static ImmutableHashSet<CapabilityIdentifier> Oid4VpCapabilities { get; } =
        ImmutableHashSet.Create(
            WellKnownCapabilityIdentifiers.VcVerifiablePresentation,
            WellKnownCapabilityIdentifiers.OAuthJwksEndpoint,
            WellKnownCapabilityIdentifiers.OAuthDiscoveryEndpoint);


    /// <summary>
    /// Drives the SD-CWT OID4VP cross-device flow over the real Kestrel wire — PAR, the wallet's
    /// HTTP GET of the JAR, and the encrypted <c>direct_post</c> — and asserts the verifier reaches
    /// <see cref="PresentationVerifiedState"/> with the expected disclosed (and withheld) claims.
    /// </summary>
    [TestMethod]
    public async Task CrossDeviceSdCwtFlowReachesPresentationVerified()
    {
        //The fixture builds the host wired with the dc+sd-cwt verification seams,
        //issues the SD-CWT (holder COSE_Key in cnf), and hands back the DCQL query,
        //the KBT-signing presentation drop-out, and the verified-claims assertion
        //(which also asserts the withheld email never surfaces).
        await using FormatRun run = await SdCwtVpFixture.Format.StartAsync(
            TimeProvider, TestContext.CancellationToken).ConfigureAwait(false);
        TestHostShell app = run.App;

        using VerifierKeyMaterial verifierKeys = app.RegisterClient(
            VerifierClientId, VerifierBaseUri, Oid4VpCapabilities);

        //Build the HTTP-backed wallet first — this starts the Kestrel listener and aligns
        //the verifier registration's IssuerUri + ResponseUri to the Kestrel base, so the
        //request_uri generated by PAR and the response_uri inside the JAR both point at the
        //real listener.
        Oid4VpWalletClient walletClient = await app.CreateHttpBackedOid4VpWalletClientAsync(
            verifierKeys,
            run.Produce,
            TestHostShell.PinnedVerifierKeyResolver(verifierKeys.SigningPublicKey),
            TestContext.CancellationToken).ConfigureAwait(false);

        //Step 1: Verifier PAR with the dc+sd-cwt DCQL query. PAR is verifier-internal (no
        //wire) per OID4VP 1.0 §3.2.
        TransactionNonce nonce = new("nonce-sd-cwt-flow-01");
        (Uri requestUri, string parHandle) = await app.HandleParAsync(
            verifierKeys, nonce, run.Query, TestContext.CancellationToken).ConfigureAwait(false);

        //Step 2: Wallet HTTP GET request_uri. Real wire — Kestrel serves the JAR, the
        //verifier PDA advances to VerifierJarServed.
        using HttpResponseMessage jarResponse = await app.Host("default").SharedHttpClient!
            .GetAsync(requestUri, TestContext.CancellationToken).ConfigureAwait(false);
        jarResponse.EnsureSuccessStatusCode();
        string compactJar = await jarResponse.Content
            .ReadAsStringAsync(TestContext.CancellationToken).ConfigureAwait(false);

        //Step 3: The real wallet client (pinned-key resolver) verifies the JAR, runs
        //the DCQL engine + KBT signing behind the fixture's presentation drop-out,
        //encrypts the response, and POSTs it over the real wire — driving the verifier to
        //PresentationVerified.
        PresentationResult result = await walletClient.PresentJarAsync(
            new PresentJarOptions
            {
                CompactJar = compactJar,
                RequestUri = requestUri,
                ExpectedVerifierClientId = VerifierClientId,
                FlowId = $"wallet-sdcwt-{Guid.NewGuid():N}"
            },
            TestContext.CancellationToken).ConfigureAwait(false);

        Assert.IsInstanceOfType<ResponseSent>(result.TerminalState,
            "The cross-device SD-CWT presentation must reach the ResponseSent wallet terminal.");

        run.AssertClaims((PresentationVerifiedState)app.GetFlowState(parHandle).State);
    }


    /// <summary>
    /// Verifies that an SD-CWT whose <c>iss</c> is listed in the DCQL query's
    /// <c>trusted_authorities</c> constraint (OID4VP 1.0 §6.1.1.3) reaches
    /// <see cref="PresentationVerifiedState"/>.
    /// </summary>
    [TestMethod]
    public async Task SdCwtFlowFromTrustedAuthorityReachesPresentationVerified()
    {
        //OID4VP 1.0 §6.1.1.3: the DCQL query pins the acceptable issuer via a
        //trusted_authorities (openid_federation) constraint. The SD-CWT's iss matches,
        //so the verifier's fail-closed DcqlEvaluator check passes for the dc+sd-cwt format.
        await using FormatRun run = await SdCwtVpFixture.Format.StartAsync(
            TimeProvider, TestContext.CancellationToken).ConfigureAwait(false);

        FlowState state = await DriveFlowAsync(
            run,
            SdCwtVpFixture.BuildSdCwtTrustedAuthoritiesPreparedQuery(SdCwtVpFixture.IssuerId))
            .ConfigureAwait(false);

        Assert.IsInstanceOfType<PresentationVerifiedState>(state,
            "An SD-CWT whose issuer is in trusted_authorities must verify.");
    }


    /// <summary>
    /// Verifies that an SD-CWT whose <c>iss</c> is NOT among the DCQL query's
    /// <c>trusted_authorities</c> does not reach <see cref="PresentationVerifiedState"/>.
    /// </summary>
    [TestMethod]
    public async Task SdCwtFlowFromUntrustedAuthorityDoesNotVerify()
    {
        //The trusted_authorities list names only a stranger, so the SD-CWT's issuer is
        //not trusted. The wallet's adapter does not enforce trusted_authorities (it
        //presents normally) — a clean verifier-side rejection for the dc+sd-cwt format.
        await using FormatRun run = await SdCwtVpFixture.Format.StartAsync(
            TimeProvider, TestContext.CancellationToken).ConfigureAwait(false);

        FlowState state = await DriveFlowAsync(
            run,
            SdCwtVpFixture.BuildSdCwtTrustedAuthoritiesPreparedQuery("https://stranger.example.com"))
            .ConfigureAwait(false);

        Assert.IsNotInstanceOfType<PresentationVerifiedState>(state,
            "An SD-CWT whose issuer is not in trusted_authorities must NOT verify.");
    }


    /// <summary>
    /// Drives the verifier through PAR → JAR → encrypted direct_post for the supplied DCQL
    /// query and returns the verifier's terminal flow state. A verifier rejection surfaces as
    /// a non-200 direct_post (the wallet client throws), which is swallowed so the caller can
    /// assert on the flow state either way.
    /// </summary>
    private async Task<FlowState> DriveFlowAsync(FormatRun run, PreparedDcqlQuery query)
    {
        TestHostShell app = run.App;
        using VerifierKeyMaterial verifierKeys = app.RegisterClient(
            VerifierClientId, VerifierBaseUri, Oid4VpCapabilities);

        TransactionNonce nonce = new($"nonce-sd-cwt-ta-{Guid.NewGuid():N}");
        (Uri requestUri, string parHandle) = await app.HandleParAsync(
            verifierKeys, nonce, query, TestContext.CancellationToken).ConfigureAwait(false);

        string compactJar = await app.HandleJarRequestAsync(
            verifierKeys, parHandle, TestContext.CancellationToken).ConfigureAwait(false);

        (OAuthClient oauthClient, _, _) = app.CreateInProcessOAuthClientAndRegistration(
            verifierKeys.Registration,
            "https://wallet.example.com/cb",
            verifierKeys.Registration.IssuerUri!.ToString());

        Oid4VpWalletClient walletClient = new(
            oauthClient.Infrastructure,
            TestHostShell.BuildSlimOid4VpWalletConfiguration(
                run.Produce,
                TestHostShell.PinnedVerifierKeyResolver(verifierKeys.SigningPublicKey)));

        try
        {
            _ = await walletClient.PresentJarAsync(
                new PresentJarOptions
                {
                    CompactJar = compactJar,
                    RequestUri = requestUri,
                    ExpectedVerifierClientId = VerifierClientId,
                    FlowId = $"wallet-sdcwt-ta-{Guid.NewGuid():N}"
                },
                TestContext.CancellationToken).ConfigureAwait(false);
        }
        catch(InvalidOperationException)
        {
            //Verifier rejected the presentation (non-200 direct_post).
        }

        return app.GetFlowState(parHandle).State;
    }
}
