namespace Verifiable.Fido2;

/// <summary>
/// A relying party's preference regarding attestation conveyance during a registration ceremony.
/// </summary>
/// <remarks>
/// <see href="https://www.w3.org/TR/webauthn-3/#enum-attestation-convey">W3C Web Authentication
/// Level 3, section 5.4.7: Attestation Conveyance Preference Enumeration (enum
/// <c>AttestationConveyancePreference</c>)</see>. Like <see cref="UserVerificationRequirement"/>,
/// this is an RP-authored ceremony-options input, never parsed off the wire by
/// <c>Verifiable.Fido2</c>, so it is modeled as a plain enum rather than a <c>WellKnown*</c> string
/// class. Wire (de)serialization of the four string values is a JSON-layer concern, via
/// <see cref="WellKnownAttestationConveyancePreferences"/>.
/// </remarks>
public enum AttestationConveyancePreference
{
    /// <summary>
    /// The relying party is not interested in authenticator attestation.
    /// </summary>
    /// <remarks>
    /// <see href="https://www.w3.org/TR/webauthn-3/#dom-attestationconveyancepreference-none">W3C Web
    /// Authentication Level 3, section 5.4.7</see>. This is the CR's own IDL default.
    /// </remarks>
    None,

    /// <summary>
    /// The relying party prefers an attestation conveyance yielding verifiable attestation
    /// statements, but allows the client to decide how to obtain such attestation statements — for
    /// example replacing authenticator attestation with a private CA (Anonymization CA) or using an
    /// Anonymous Attestation Method.
    /// </summary>
    /// <remarks>
    /// <see href="https://www.w3.org/TR/webauthn-3/#dom-attestationconveyancepreference-indirect">W3C
    /// Web Authentication Level 3, section 5.4.7</see>.
    /// </remarks>
    Indirect,

    /// <summary>
    /// The relying party wants to receive the attestation statement as generated by the
    /// authenticator.
    /// </summary>
    /// <remarks>
    /// <see href="https://www.w3.org/TR/webauthn-3/#dom-attestationconveyancepreference-direct">W3C
    /// Web Authentication Level 3, section 5.4.7</see>.
    /// </remarks>
    Direct,

    /// <summary>
    /// The relying party wants to receive an attestation statement that may include uniquely
    /// identifying information, for a controlled deployment of authenticators known to the relying
    /// party.
    /// </summary>
    /// <remarks>
    /// <see href="https://www.w3.org/TR/webauthn-3/#dom-attestationconveyancepreference-enterprise">
    /// W3C Web Authentication Level 3, section 5.4.7</see>.
    /// </remarks>
    Enterprise
}
