using System.Diagnostics;

namespace Verifiable.Fido2;

/// <summary>
/// Records that a <see cref="NoneAttestationResult"/> is not a genuine <c>none</c> attestation
/// statement, but a certified attestation the relying party's downgrade policy accepted as
/// none-equivalent after its trust path failed to reach a supplied anchor.
/// </summary>
/// <param name="Format">
/// The attestation statement format identifier (<c>fmt</c>) that was downgraded — <c>packed</c>,
/// <c>android-key</c>, or <c>fido-u2f</c>.
/// </param>
/// <param name="OriginalError">
/// The trust-path shortfall that triggered the downgrade —
/// <see cref="Fido2AttestationErrors.NoTrustAnchors"/> or
/// <see cref="Fido2AttestationErrors.ChainValidationFailed"/>; never a signature or format
/// violation, which never downgrades.
/// </param>
/// <remarks>
/// <see href="https://www.w3.org/TR/webauthn-3/#sctn-registering-a-new-credential">W3C Web
/// Authentication Level 3, section 7.1: Registering a New Credential</see>, the ceremony's final
/// step (step 29): "If the Relying Party does not fail the registration ceremony in this case,
/// then the Relying Party is accepting that there is no cryptographic proof that the public key
/// credential has been generated by any particular authenticator model. The Relying Party MAY
/// consider the credential as equivalent to one with no attestation" (cross-referencing
/// <see href="https://www.w3.org/TR/webauthn-3/#sctn-attestation-types">section 6.5.3: Attestation
/// Types</see>). Carried by <see cref="NoneAttestationResult.Downgrade"/> and, on the same
/// registration, the <see cref="Fido2ClaimIds.Fido2RegistrationAttestationDowngraded"/> claim's
/// <see cref="Fido2AttestationDowngradeClaimContext"/>, so a relying party can audit that this
/// specific credential carries no cryptographic attestation assurance beyond the base credential
/// key signature every ceremony already has.
/// </remarks>
[DebuggerDisplay("Fido2AttestationDowngrade({Format,nq}: {OriginalError.Code,nq})")]
public sealed record Fido2AttestationDowngrade(string Format, Fido2AttestationError OriginalError);
