using System.Buffers;
using System.Buffers.Text;
using Verifiable.Cryptography;

namespace Verifiable.Fido2;

/// <summary>
/// Generates WebAuthn cryptographic challenges through the registered entropy provider.
/// </summary>
/// <remarks>
/// <para>
/// <see href="https://www.w3.org/TR/webauthn-3/#sctn-cryptographic-challenges">W3C Web
/// Authentication Level 3, section 13.4.3: Cryptographic Challenges</see>: "the values of both
/// <c>PublicKeyCredentialCreationOptions.challenge</c> and
/// <c>PublicKeyCredentialRequestOptions.challenge</c> MUST be randomly generated by Relying
/// Parties" and "the challenges MUST contain enough entropy to make guessing them infeasible" —
/// both MUST-level. The same section adds "Challenges SHOULD therefore be at least 16 bytes
/// long" — a SHOULD-level figure, not a MUST-level floor; this class enforces it anyway as its
/// minimum, following this codebase's "secure default when principled" convention, and defaults
/// to 32 bytes (256 bits of entropy) mirroring <c>Verifiable.OAuth.Pkce.PkceGeneration</c>'s own
/// judgment call for its verifier length.
/// </para>
/// <para>
/// This is the provider-agnostic entropy seam every other consumer in this codebase calls —
/// <see cref="CryptographicKeyEvents.GenerateNonce(int, Tag, MemoryPool{byte}, string?)"/> — not the
/// provider-internal <c>FillEntropyDelegate</c>/<c>Nonce.Generate</c> pair those providers use
/// internally. Calling the low-level pair directly would bypass the registered-provider
/// indirection and the <see cref="CryptoEvent"/> emission the CBOM observability wiring depends on.
/// </para>
/// </remarks>
public static class Fido2ChallengeGeneration
{
    /// <summary>
    /// The default challenge length in bytes. 32 bytes (256 bits of entropy) comfortably exceeds
    /// the CR §13.4.3 SHOULD-level 16-byte figure, mirroring
    /// <c>Verifiable.OAuth.Pkce.PkceGeneration</c>'s own 32-byte default for the same reasoning.
    /// </summary>
    private const int DefaultByteLength = 32;

    /// <summary>
    /// The minimum challenge length in bytes this class accepts. CR §13.4.3 phrases 16 bytes as a
    /// SHOULD, not a MUST, but this codebase's secure-default convention enforces it as a floor
    /// rather than letting a caller silently request an arbitrarily short, weak challenge.
    /// </summary>
    private const int MinimumByteLength = 16;


    /// <summary>
    /// Generates a WebAuthn challenge of the default length (<see cref="DefaultByteLength"/> bytes).
    /// </summary>
    /// <param name="pool">The memory pool the challenge bytes are rented from.</param>
    /// <returns>The Base64url-encoded challenge, matching the shape
    /// <see cref="RegistrationCeremonyInput.ExpectedChallenge"/> and
    /// <see cref="AssertionCeremonyInput.ExpectedChallenge"/> already require.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="pool"/> is <see langword="null"/>.</exception>
    public static string Generate(MemoryPool<byte> pool) => Generate(DefaultByteLength, pool);


    /// <summary>
    /// Generates a WebAuthn challenge of <paramref name="byteLength"/> bytes through the registered
    /// entropy provider.
    /// </summary>
    /// <param name="byteLength">
    /// The number of random bytes to generate. Must be at least <see cref="MinimumByteLength"/>
    /// (16 bytes, the CR §13.4.3 SHOULD-level figure).
    /// </param>
    /// <param name="pool">The memory pool the challenge bytes are rented from.</param>
    /// <returns>
    /// The Base64url-encoded challenge (no padding, via <see cref="Base64Url"/>), matching the
    /// shape <see cref="RegistrationCeremonyInput.ExpectedChallenge"/> and
    /// <see cref="AssertionCeremonyInput.ExpectedChallenge"/> already require. The raw challenge
    /// bytes are rented, filled, consumed, and released before this method returns — only the
    /// encoded string escapes, matching <c>PkceGeneration</c>'s own carrier discipline.
    /// </returns>
    /// <exception cref="ArgumentOutOfRangeException">
    /// <paramref name="byteLength"/> is less than <see cref="MinimumByteLength"/>.
    /// </exception>
    /// <exception cref="ArgumentNullException"><paramref name="pool"/> is <see langword="null"/>.</exception>
    public static string Generate(int byteLength, MemoryPool<byte> pool)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(byteLength, MinimumByteLength);
        ArgumentNullException.ThrowIfNull(pool);

        using Nonce challenge = CryptographicKeyEvents.GenerateNonce(byteLength, Fido2Tags.Challenge, pool);

        return Base64Url.EncodeToString(challenge.UseNonce());
    }
}
