using Verifiable.Core.Automata;
using Verifiable.OAuth.AuthCode.States;
using Verifiable.OAuth.Oid4Vp.Wallet.States;
using Verifiable.OAuth.Server;

namespace Verifiable.OAuth.Oid4Vp.Wallet;

/// <summary>
/// Factory for the Wallet-side OID4VP presentation flow pushdown automaton.
/// </summary>
/// <remarks>
/// <para>
/// The PDA produced by <see cref="Create"/> models the Wallet's steps from receiving a
/// <c>request_uri</c> through POSTing the encrypted Authorization Response. Each call to
/// <c>StepAsync</c> corresponds to one logical operation in the Wallet's presentation
/// flow, and the resulting state snapshot can be persisted between operations.
/// </para>
/// <para>
/// The accept predicate matches <see cref="ResponseSent"/> (cross-device) or
/// <see cref="BrowserRedirectIssued"/> (same-device): the Wallet has successfully
/// completed its side of the protocol.
/// </para>
/// </remarks>
public static class WalletFlowAutomaton
{
    /// <summary>
    /// Creates a new Wallet-side OID4VP presentation flow PDA.
    /// </summary>
    /// <param name="runId">
    /// A unique identifier for this PDA instance. Appears in every
    /// <see cref="TraceEntry{TState,TInput}"/> emitted by the observable.
    /// </param>
    /// <param name="requestUri">
    /// The <c>request_uri</c> from the QR code or deep link that initiates the flow.
    /// </param>
    /// <param name="expectedVerifierClientId">
    /// The Verifier client identifier the Wallet expects to see in the JAR.
    /// Used for mix-up defense — the Wallet rejects JARs whose <c>client_id</c>
    /// does not match.
    /// </param>
    /// <param name="flowId">
    /// Stable identifier for this presentation flow instance. Typically a UUID
    /// generated by the Wallet at QR-scan time.
    /// </param>
    /// <param name="timeProvider">Time provider for expiry computation.</param>
    /// <param name="maxFlowDuration">
    /// Maximum duration the Wallet waits before treating the flow as expired.
    /// Defaults to five minutes.
    /// </param>
    public static PushdownAutomaton<OAuthFlowState, OAuthFlowInput, WalletFlowStackSymbol> Create(
        string runId,
        Uri requestUri,
        string expectedVerifierClientId,
        string flowId,
        TimeProvider timeProvider,
        TimeSpan? maxFlowDuration = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(runId);
        ArgumentNullException.ThrowIfNull(requestUri);
        ArgumentException.ThrowIfNullOrWhiteSpace(expectedVerifierClientId);
        ArgumentException.ThrowIfNullOrWhiteSpace(flowId);
        ArgumentNullException.ThrowIfNull(timeProvider);

        DateTimeOffset now = timeProvider.GetUtcNow();
        TimeSpan duration = maxFlowDuration ?? TimeSpan.FromMinutes(5);

        return new PushdownAutomaton<OAuthFlowState, OAuthFlowInput, WalletFlowStackSymbol>(
            runId: runId,
            initialState: new RequestUriReceived
            {
                FlowId = flowId,
                ExpectedIssuer = expectedVerifierClientId,
                EnteredAt = now,
                ExpiresAt = now.Add(duration),
                Kind = FlowKind.Wallet,
                RequestUri = requestUri
            },
            initialStackSymbol: WalletFlowStackSymbol.Base,
            transition: WalletFlowTransitions.Create(),
            acceptPredicate: static state => state is ResponseSent or BrowserRedirectIssued,
            timeProvider: timeProvider);
    }


    /// <summary>
    /// Restores a Wallet-side OID4VP presentation flow automaton from a persisted
    /// state snapshot.
    /// </summary>
    /// <param name="state">The persisted flow state, typically loaded from a database.</param>
    /// <param name="stepCount">The step count at the time the state was persisted.</param>
    /// <param name="timeProvider">The time provider used for expiry checks.</param>
    public static PushdownAutomaton<OAuthFlowState, OAuthFlowInput, WalletFlowStackSymbol> CreateFromSnapshot(
        OAuthFlowState state,
        int stepCount,
        TimeProvider timeProvider)
    {
        ArgumentNullException.ThrowIfNull(state);
        ArgumentNullException.ThrowIfNull(timeProvider);

        return new PushdownAutomaton<OAuthFlowState, OAuthFlowInput, WalletFlowStackSymbol>(
            runId: Guid.NewGuid().ToString(),
            savedState: state,
            savedStack: [WalletFlowStackSymbol.Base],
            savedStepCount: stepCount,
            transition: WalletFlowTransitions.Create(),
            acceptPredicate: static s => s is ResponseSent or BrowserRedirectIssued,
            timeProvider: timeProvider);
    }
}
