using System;
using System.Diagnostics;
using Verifiable.Cryptography.Context;

namespace Verifiable.Cryptography;

/// <summary>
/// Base record for all observable cryptographic events emitted by this library.
/// </summary>
/// <remarks>
/// <para>
/// Events are emitted by cryptographic operations (entropy generation, signing,
/// verification, key material creation) and consumed by application-provided
/// subscribers via <see cref="CryptoObservable.Events"/>. The library does not
/// own the bus, transport, or sink — those are application concerns.
/// </para>
/// <para>
/// <strong>Correlation via W3C TraceContext.</strong>
/// </para>
/// <para>
/// <see cref="TraceParent"/> carries the W3C <c>traceparent</c> header value
/// from <see cref="Activity.Current"/> at the time the event is constructed.
/// When an OTel trace is active this threads the event into the distributed
/// trace automatically — including through claims assessment, DB writes, and
/// remote calls. When no trace is active, <see cref="TraceParent"/> is
/// <see langword="null"/>, which is honest: no trace is active, so no trace
/// context is available.
/// </para>
/// <para>
/// Events can be forwarded as CloudEvents, anchored to a Merkle log,
/// or correlated with did:cel / did:keri entries using <see cref="EventId"/>
/// and <see cref="TraceParent"/> as external identifiers.
/// </para>
/// </remarks>
public abstract record CryptoEvent
{
    /// <summary>
    /// Unique identifier for this event. Can be referenced by external
    /// audit logs, Merkle trees, or did:cel entries.
    /// </summary>
    public Guid EventId { get; init; } = Guid.NewGuid();

    /// <summary>
    /// When the event occurred.
    /// </summary>
    public DateTimeOffset OccurredAt { get; init; }

    /// <summary>
    /// The component or entity that emitted this event. Typically a DID when
    /// available (e.g. <c>did:web:issuer.example.com</c>), or a library
    /// component name when no DID context is active.
    /// </summary>
    public string EmittedBy { get; init; } = string.Empty;

    /// <summary>
    /// W3C TraceContext <c>traceparent</c> header value captured from
    /// <see cref="Activity.Current"/> at event construction time.
    /// <see langword="null"/> when no OTel activity is active.
    /// </summary>
    public string? TraceParent { get; init; }

    /// <summary>
    /// W3C TraceContext <c>tracestate</c> header value.
    /// <see langword="null"/> when no OTel activity is active.
    /// </summary>
    public string? TraceState { get; init; }


    /// <summary>
    /// Captures the current W3C TraceContext from <see cref="Activity.Current"/>.
    /// Call this at event construction time inside the operation being observed.
    /// </summary>
    protected static (string? traceParent, string? traceState) CaptureTraceContext() =>
        (Activity.Current?.Id, Activity.Current?.TraceStateString);
}


/// <summary>
/// Emitted when cryptographically random bytes are drawn from an entropy source.
/// </summary>
/// <remarks>
/// Carries the source identity, byte count, purpose, and the health snapshot
/// of the source at the moment of generation. Together these form the
/// generation-time entropy provenance record that travels with the produced
/// <see cref="Nonce"/>, <see cref="Salt"/>, or other value via its
/// <see cref="Tag"/>.
/// </remarks>
public sealed record EntropyConsumedEvent: CryptoEvent
{
    /// <summary>The source that produced the bytes.</summary>
    public EntropySource Source { get; init; }

    /// <summary>How many bytes were drawn.</summary>
    public int ByteCount { get; init; }

    /// <summary>The purpose of the generated bytes (e.g. <see cref="Purpose.Nonce"/>).</summary>
    public Purpose Purpose { get; init; }

    /// <summary>
    /// Health of the source at the moment of generation. Carries the
    /// assessment that was most recently available — not necessarily
    /// performed at this exact instant.
    /// </summary>
    public EntropyHealthObservation HealthAtGeneration { get; init; } = EntropyHealthObservation.Unknown;


    /// <summary>
    /// Constructs an <see cref="EntropyConsumedEvent"/> capturing the current
    /// trace context automatically.
    /// </summary>
    public static EntropyConsumedEvent Create(
        EntropySource source,
        int byteCount,
        Purpose purpose,
        EntropyHealthObservation health,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new EntropyConsumedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            Source = source,
            ByteCount = byteCount,
            Purpose = purpose,
            HealthAtGeneration = health,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// Emitted when a health assessment of an entropy source is performed.
/// </summary>
/// <remarks>
/// Distinct from the health snapshot embedded in <see cref="EntropyConsumedEvent"/>
/// — this event represents a dedicated assessment action, not a by-product of
/// byte generation. Carries the method, assessor, time window, and optional
/// evidence reference.
/// </remarks>
public sealed record EntropyHealthAssessedEvent: CryptoEvent
{
    /// <summary>The source that was assessed.</summary>
    public EntropySource Source { get; init; }

    /// <summary>The observation produced by this assessment.</summary>
    public EntropyHealthObservation Observation { get; init; } = EntropyHealthObservation.Unknown;

    /// <summary>
    /// Constructs an <see cref="EntropyHealthAssessedEvent"/> capturing the
    /// current trace context automatically.
    /// </summary>
    public static EntropyHealthAssessedEvent Create(
        EntropySource source,
        EntropyHealthObservation observation,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new EntropyHealthAssessedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            Source = source,
            Observation = observation,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// Emitted when key material is generated. Carries algorithm and backend
/// metadata only — never raw key bytes.
/// </summary>
public sealed record KeyMaterialGeneratedEvent: CryptoEvent
{
    /// <summary>The cryptographic algorithm of the generated material.</summary>
    public CryptoAlgorithm Algorithm { get; init; }

    /// <summary>The purpose of the generated key (signing, verification, exchange).</summary>
    public Purpose Purpose { get; init; }

    /// <summary>
    /// How the bytes should be interpreted — direct material or a hardware handle.
    /// </summary>
    public MaterialSemantics MaterialSemantics { get; init; }

    /// <summary>
    /// The library or backend that performed the generation, e.g. "BouncyCastle",
    /// "MicrosoftCng", "NSec". Opaque string — the library cannot introspect
    /// third-party key generation internals.
    /// </summary>
    public string Backend { get; init; } = string.Empty;


    /// <summary>
    /// Constructs a <see cref="KeyMaterialGeneratedEvent"/> capturing the
    /// current trace context automatically.
    /// </summary>
    public static KeyMaterialGeneratedEvent Create(
        CryptoAlgorithm algorithm,
        Purpose purpose,
        MaterialSemantics materialSemantics,
        string backend,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new KeyMaterialGeneratedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            Algorithm = algorithm,
            Purpose = purpose,
            MaterialSemantics = materialSemantics,
            Backend = backend,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// Emitted when a signing operation completes. Carries algorithm and size
/// metadata only — never the signed data or signature bytes.
/// </summary>
public sealed record SignatureProducedEvent: CryptoEvent
{
    /// <summary>The algorithm used to produce the signature.</summary>
    public CryptoAlgorithm Algorithm { get; init; }

    /// <summary>Length in bytes of the data that was signed.</summary>
    public int DataLength { get; init; }

    /// <summary>Length in bytes of the produced signature.</summary>
    public int SignatureLength { get; init; }

    /// <summary>The backend that performed the signing operation.</summary>
    public string Backend { get; init; } = string.Empty;


    /// <summary>
    /// Constructs a <see cref="SignatureProducedEvent"/> capturing the
    /// current trace context automatically.
    /// </summary>
    public static SignatureProducedEvent Create(
        CryptoAlgorithm algorithm,
        int dataLength,
        int signatureLength,
        string backend,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new SignatureProducedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            Algorithm = algorithm,
            DataLength = dataLength,
            SignatureLength = signatureLength,
            Backend = backend,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// Emitted when a signature verification operation completes.
/// </summary>
/// <remarks>
/// A <see cref="VerificationOutcome.Invalid"/> result in a regulated flow
/// is a security event and should be treated accordingly by the subscriber.
/// </remarks>
public sealed record VerificationCompletedEvent: CryptoEvent
{
    /// <summary>The algorithm used for verification.</summary>
    public CryptoAlgorithm Algorithm { get; init; }

    /// <summary>Whether verification succeeded, failed, or encountered an error.</summary>
    public VerificationOutcome Outcome { get; init; }

    /// <summary>Length in bytes of the data that was verified.</summary>
    public int DataLength { get; init; }

    /// <summary>The backend that performed the verification.</summary>
    public string Backend { get; init; } = string.Empty;


    /// <summary>
    /// Constructs a <see cref="VerificationCompletedEvent"/> capturing the
    /// current trace context automatically.
    /// </summary>
    public static VerificationCompletedEvent Create(
        CryptoAlgorithm algorithm,
        VerificationOutcome outcome,
        int dataLength,
        string backend,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new VerificationCompletedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            Algorithm = algorithm,
            Outcome = outcome,
            DataLength = dataLength,
            Backend = backend,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// Emitted when a digest (hash) is computed.
/// </summary>
public sealed record DigestComputedEvent: CryptoEvent
{
    /// <summary>The algorithm used (e.g. SHA-256).</summary>
    public string AlgorithmName { get; init; } = string.Empty;

    /// <summary>Length in bytes of the input data.</summary>
    public int InputLength { get; init; }

    /// <summary>Length in bytes of the produced digest.</summary>
    public int DigestLength { get; init; }

    /// <summary>The purpose of this digest (e.g. PKCE challenge, JWK thumbprint).</summary>
    public Purpose Purpose { get; init; }


    /// <summary>
    /// Constructs a <see cref="DigestComputedEvent"/> capturing the current
    /// trace context automatically.
    /// </summary>
    public static DigestComputedEvent Create(
        string algorithmName,
        int inputLength,
        int digestLength,
        Purpose purpose,
        string emittedBy = "",
        TimeProvider? timeProvider = null)
    {
        (string? traceParent, string? traceState) = CaptureTraceContext();
        return new DigestComputedEvent
        {
            OccurredAt = (timeProvider ?? TimeProvider.System).GetUtcNow(),
            AlgorithmName = algorithmName,
            InputLength = inputLength,
            DigestLength = digestLength,
            Purpose = purpose,
            EmittedBy = emittedBy,
            TraceParent = traceParent,
            TraceState = traceState
        };
    }
}


/// <summary>
/// The outcome of a cryptographic signature verification operation.
/// </summary>
public enum VerificationOutcome
{
    /// <summary>Signature is cryptographically valid.</summary>
    Valid,

    /// <summary>
    /// Signature is not valid. In a regulated flow this is a security event.
    /// </summary>
    Invalid,

    /// <summary>
    /// Verification could not be completed due to an error (missing key,
    /// unsupported algorithm, etc.).
    /// </summary>
    Error
}