using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Verifiable.Core.Assessment
{
    /// <summary>
    /// Delegate to archive an <see cref="AssessmentResult"/>.
    /// </summary>
    /// <param name="assessmentToArchive">The assessment result to archive.</param>
    /// <param name="archiverId">Identifier for the archiver.</param>
    /// <param name="creationTimestamp">
    /// UTC timestamp for the archiving operation. Provided by the caller's time source.
    /// </param>
    /// <param name="traceId">Tracing identifier for the archival operation.</param>
    /// <param name="spanId">Span identifier for the archival operation.</param>
    /// <param name="baggage">Additional context for the archival operation.</param>
    /// <param name="cancellationToken">Token to monitor for cancellation requests.</param>
    /// <returns>The archiving result.</returns>
    /// <remarks>
    /// <para>
    /// Archiving delegates persist assessment results for long-term storage, audit trails,
    /// and compliance requirements. The archive destination is implementation-specific and
    /// could be a database, file system, distributed ledger, or external service.
    /// </para>
    /// <para>
    /// <strong>Time Handling:</strong>
    /// </para>
    /// <para>
    /// The <paramref name="creationTimestamp"/> is provided by the caller rather than generated
    /// internally. This ensures full testability and allows the caller to control the time source.
    /// </para>
    /// </remarks>
    public delegate ValueTask<ArchivingResult> ArchiveDelegateAsync(
        AssessmentResult assessmentToArchive,
        string archiverId,
        DateTime creationTimestamp,
        string? traceId,
        string? spanId,
        IReadOnlyDictionary<string, string>? baggage,
        CancellationToken cancellationToken = default);


    /// <summary>
    /// The context in which assessment results are archived.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="ArchiveContext"/> may hold information such as archival rules, destination
    /// storage configuration, retention policies, and other relevant data ensuring the proper
    /// archiving of claims and assessments. Extend this class to capture domain-specific
    /// archival context.
    /// </para>
    /// </remarks>
    public class ArchiveContext
    {
    }


    /// <summary>
    /// Represents the result of an archiving operation.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The <see cref="ArchivingResult"/> record captures important metadata about the archiving
    /// operation, providing a comprehensive audit trail that includes:
    /// </para>
    /// <list type="bullet">
    /// <item><description>
    /// A unique <see cref="ArchiveId"/> generated by the archiving process to identify the
    /// archived data.
    /// </description></item>
    /// <item><description>
    /// A user-supplied <see cref="CorrelationId"/> to correlate the archive operation with
    /// other operations, logs, or transactions.
    /// </description></item>
    /// <item><description>
    /// Tracing information for distributed systems (trace ID, span ID, baggage).
    /// </description></item>
    /// <item><description>
    /// Archiver version information for tracking archival logic changes.
    /// </description></item>
    /// </list>
    /// <para>
    /// <strong>Time Handling:</strong>
    /// </para>
    /// <para>
    /// The <see cref="CreationTimestampInUtc"/> is provided by the caller's time source,
    /// ensuring consistency and testability.
    /// </para>
    /// </remarks>
    /// <param name="IsSuccess">Indicates if the archiving was successful.</param>
    /// <param name="ArchivingId">Identifier for this particular archiving result.</param>
    /// <param name="ArchiveId">
    /// Unique identifier for the archive, generated by the archiver to identify the stored data.
    /// </param>
    /// <param name="CorrelationId">
    /// User-supplied identifier to correlate the archive operation with other operations.
    /// </param>
    /// <param name="ArchiverVersion">Version information of the archiver.</param>
    /// <param name="CreationTimestampInUtc">
    /// UTC timestamp indicating when the archiving operation was completed. Provided by the
    /// caller's time source.
    /// </param>
    /// <param name="ArchivingContext">Context data related to the archiving operation.</param>
    /// <param name="TraceId">Tracing identifier for the archival operation.</param>
    /// <param name="SpanId">Span identifier for the archival operation.</param>
    /// <param name="Baggage">Additional context for the archival operation.</param>
    public record ArchivingResult(
        bool IsSuccess,
        string ArchivingId,
        string ArchiveId,
        string CorrelationId,
        string ArchiverVersion,
        DateTime CreationTimestampInUtc,
        ArchiveContext ArchivingContext,
        string? TraceId,
        string? SpanId,
        IReadOnlyDictionary<string, string>? Baggage);
}