using System;
using System.Collections.Generic;

namespace Verifiable.Core.Assessment
{
    /// <summary>
    /// The data or conditions upon which claims are based.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="ClaimIssueResultContext"/> captures the inputs and conditions that were used
    /// during claim generation, enabling full traceability and reproducibility of the validation
    /// process.
    /// </para>
    /// </remarks>
    public class ClaimIssueResultContext
    {
        /// <summary>
        /// Gets or sets the inputs used for the claim generation operation.
        /// </summary>
        /// <remarks>
        /// <para>
        /// The inputs are stored as <see cref="object"/> to accommodate various input types.
        /// Consumers should cast to the appropriate type based on the <see cref="ClaimIssuer{TInput}"/>
        /// that generated this result.
        /// </para>
        /// </remarks>
        public object? Inputs { get; set; }
    }


    /// <summary>
    /// Indicates the completion status of a claim generation operation.
    /// </summary>
    public enum ClaimIssueCompletionStatus
    {
        /// <summary>
        /// All validation rules were executed successfully.
        /// </summary>
        Complete,

        /// <summary>
        /// The operation was cancelled before all validation rules could execute.
        /// The <see cref="ClaimIssueResult.Claims"/> contains only claims generated before cancellation.
        /// </summary>
        Cancelled,

        /// <summary>
        /// The operation timed out before all validation rules could execute.
        /// The <see cref="ClaimIssueResult.Claims"/> contains only claims generated before timeout.
        /// </summary>
        TimedOut
    }


    /// <summary>
    /// Consolidates the outputs of a claim generation step, including the claims themselves,
    /// tracing identifiers, completion status, and any extra metadata.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="ClaimIssueResult"/> makes it possible to follow the validation process across
    /// multiple steps from where it started to where it ended. This record is designed to be
    /// passed to subsequent stages of the validation and assessment pipeline, potentially
    /// including archival or further analysis.
    /// </para>
    /// <para>
    /// <strong>Partial Results:</strong>
    /// </para>
    /// <para>
    /// When cancellation is requested during claim generation, the <see cref="ClaimIssuer{TInput}"/>
    /// returns a <see cref="ClaimIssueResult"/> containing the claims generated before cancellation
    /// occurred. The <see cref="CompletionStatus"/> property indicates whether the result is complete
    /// or partial, and <see cref="RulesExecuted"/> and <see cref="TotalRules"/> provide details about
    /// how much of the validation was completed.
    /// </para>
    /// <para>
    /// <strong>Time Handling:</strong>
    /// </para>
    /// <para>
    /// The <see cref="CreationTimestampInUtc"/> is provided by the caller's time source (typically
    /// via <see cref="TimeProvider"/>). The library never generates timestamps internally, ensuring
    /// full testability and determinism.
    /// </para>
    /// </remarks>
    /// <param name="ClaimIssueResultId">
    /// Unique identifier for this issued <see cref="ClaimIssueResult"/>. Generated by the
    /// <see cref="GenerateClaimIdAsync"/> delegate provided to the <see cref="ClaimIssuer{TInput}"/>.
    /// </param>
    /// <param name="ClaimIssuerId">
    /// Identifier for the <see cref="ClaimIssuer{TInput}"/> that generated this result.
    /// </param>
    /// <param name="CorrelationId">
    /// User-supplied identifier to correlate claim generation with other operations.
    /// </param>
    /// <param name="Claims">
    /// List of claims generated. May be partial if <see cref="CompletionStatus"/> is not
    /// <see cref="ClaimIssueCompletionStatus.Complete"/>.
    /// </param>
    /// <param name="CreationTimestampInUtc">
    /// UTC timestamp indicating when the claim results were generated. Provided by the caller's
    /// time source, not generated internally.
    /// </param>
    /// <param name="CompletionStatus">
    /// Indicates whether all validation rules were executed or if the operation was cancelled
    /// or timed out.
    /// </param>
    /// <param name="RulesExecuted">
    /// The number of validation rules that were executed before the operation completed or was
    /// cancelled.
    /// </param>
    /// <param name="TotalRules">
    /// The total number of validation rules that were configured to execute.
    /// </param>
    /// <param name="IssuingContext">
    /// Optional context data related to the issuing process, including the inputs that were
    /// validated.
    /// </param>
    /// <param name="ClaimIssuerTraceId">
    /// Tracing identifier for the claim generation operation, compatible with OpenTelemetry
    /// and W3C Trace Context.
    /// </param>
    /// <param name="ClaimIssuerSpanId">
    /// Span identifier for the claim generation operation, compatible with OpenTelemetry
    /// and W3C Trace Context.
    /// </param>
    /// <param name="Baggage">
    /// Additional context for the claim generation operation, propagated across service
    /// boundaries.
    /// </param>
    public record ClaimIssueResult(
        string ClaimIssueResultId,
        string ClaimIssuerId,
        string CorrelationId,
        IList<Claim> Claims,
        DateTime CreationTimestampInUtc,
        ClaimIssueCompletionStatus CompletionStatus,
        int RulesExecuted,
        int TotalRules,
        ClaimIssueResultContext? IssuingContext = null,
        string? ClaimIssuerTraceId = null,
        string? ClaimIssuerSpanId = null,
        IReadOnlyDictionary<string, string>? Baggage = null)
    {
        /// <summary>
        /// Gets a value indicating whether all configured validation rules were executed.
        /// </summary>
        public bool IsComplete => CompletionStatus == ClaimIssueCompletionStatus.Complete;
    }
}