using System.Diagnostics;

namespace Verifiable.OAuth.Server.Pipeline;

/// <summary>
/// Well-known context bag key constants for Authorization Server request processing.
/// </summary>
/// <remarks>
/// <para>
/// The application skin places request-shaped values into the context bag before
/// calling <see cref="AuthorizationServer.DispatchAsync"/>. The dispatcher and the
/// application's resolution delegates read them via the typed accessors on
/// <see cref="ExchangeContextServerExtensions"/>.
/// </para>
/// <para>
/// The context bag is typed as <see cref="System.Collections.Generic.Dictionary{TKey, TValue}"/>
/// of <see cref="string"/> to <see cref="object"/> to avoid coupling the library to
/// ASP.NET or any other HTTP framework. Library users add their own typed accessors
/// using C# 14 extension syntax — the methods appear alongside the library-provided
/// ones in IntelliSense.
/// </para>
/// </remarks>
[DebuggerDisplay("AuthorizationServerHandlers")]
internal static class AuthorizationServerHandlers
{
    /// <summary>
    /// Context bag key for the capability of the matched endpoint. Set by the
    /// dispatcher after the chain walk produces a non-<see langword="null"/>
    /// match, reading <see cref="ServerEndpoint.Capability"/> from the winning
    /// endpoint. Read by post-match telemetry, observability, and audit code.
    /// Not a routing input — Phase 4 made capability descriptive metadata
    /// rather than a chain-walk filter.
    /// Value type: <see cref="CapabilityIdentifier"/>.
    /// </summary>
    public const string CapabilityKey = "server.capability";

    //The TenantId context key + accessor now live in Core's
    //ExchangeContextExtensions over the neutral context (tenancy is
    //cross-cutting); read/write tenant identity via context.TenantId /
    //context.SetTenantId(...).

    /// <summary>
    /// Context bag key for the server issuer URI.
    /// Value type: <see cref="Uri"/>.
    /// </summary>
    public const string IssuerKey = "server.issuer";

    /// <summary>
    /// Context bag key for the authenticated subject identifier.
    /// Value type: <see cref="string"/>.
    /// Set by the application's authentication middleware before dispatching to
    /// the authorize endpoint.
    /// </summary>
    public const string SubjectIdKey = "server.subjectId";

    /// <summary>
    /// Context bag key for the authentication time.
    /// Value type: <see cref="DateTimeOffset"/>.
    /// </summary>
    public const string AuthTimeKey = "server.authTime";

    /// <summary>
    /// Context bag key for the End-User's authentication session identifier (<c>sid</c>),
    /// stamped by the application's authentication middleware at authorize time alongside
    /// <see cref="AuthTimeKey"/>. Value type: <see cref="string"/>.
    /// </summary>
    public const string SessionIdKey = "server.sessionId";

    /// <summary>
    /// Context bag key for the Authentication Context Class Reference (<c>acr</c>)
    /// established for the End-User's authentication, stamped by the application's
    /// authentication middleware at authorize time alongside <see cref="AuthTimeKey"/>.
    /// Carried into the access token's <c>acr</c> claim per RFC 9068 §2.2.1 / RFC 9470 §5.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public const string AcrKey = "server.acr";

    /// <summary>
    /// Context bag key for the <see cref="ClientRecord"/> resolved at the start
    /// of each request. Set by the dispatcher so <c>BuildInputAsync</c> delegates can
    /// read per-registration values without capturing from outside static lambdas.
    /// Value type: <see cref="ClientRecord"/>.
    /// </summary>
    public const string RegistrationKey = "server.registration";

    /// <summary>
    /// Context bag key for the flow identifier. Set by <see cref="BuildInputDelegate"/>
    /// implementations on continuing-flow endpoints so the dispatcher can load the
    /// correct state from the store.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public const string FlowIdKey = "server.flowId";

    /// <summary>
    /// Context bag output key for the correlation key generated by
    /// <see cref="BuildInputDelegate"/> on new-flow endpoints.
    /// The dispatcher reads this after <c>BuildInputAsync</c> runs on new flows
    /// to determine the storage key for <see cref="SaveServerFlowStateDelegate"/>.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public const string CorrelationKeyOutputKey = "server.correlationKey";

    /// <summary>
    /// Context bag key for the UTC instant at which effectful verification completed.
    /// Set by the dispatcher before executing the <see cref="OAuthActionExecutor"/>
    /// so action handlers can timestamp results without calling
    /// <c>DateTimeOffset.UtcNow</c> directly.
    /// Value type: <see cref="System.DateTimeOffset"/>.
    /// </summary>
    public const string VerifiedAtKey = "server.verifiedAt";

    /// <summary>
    /// Context key for accumulated validation results produced during request processing.
    /// Value type: <see cref="System.Collections.Generic.List{T}"/> of
    /// <see cref="Verifiable.Core.Assessment.ClaimIssueResult"/>.
    /// </summary>
    public const string ValidationResultsKey = "server.validationResults";

    /// <summary>
    /// Context-bag key for the <see cref="IssuedTokenSet"/> assembled by the
    /// token endpoint's <c>BuildInputAsync</c> for consumption by
    /// <c>BuildResponse</c>.
    /// </summary>
    /// <remarks>
    /// Token strings are transient — they live on the context bag for the
    /// duration of a single request. The PDA state and persisted flow record
    /// carry only audit metadata (jti, signing key id, issued-at, expires-at)
    /// keyed by token-type response field name.
    /// </remarks>
    public const string IssuedTokensKey = "server.issuedTokens";

    /// <summary>
    /// Context-bag key for the granted RFC 9396 <c>authorization_details</c> response value
    /// (the serialised JSON array carrying the OID4VCI 1.0 §6.2 <c>credential_identifiers</c>)
    /// assembled by the token endpoint's <c>BuildInputAsync</c> for consumption by
    /// <c>BuildResponse</c>. Transient, like the issued token strings — never persisted.
    /// </summary>
    public const string GrantedAuthorizationDetailsKey = "server.grantedAuthorizationDetails";

    /// <summary>
    /// Context-bag key for the granted RFC 9396 <c>authorization_details</c> in structured form
    /// — a list of authorization details objects, each a string-keyed map — assembled by the token
    /// endpoint's <c>BuildInputAsync</c> alongside <see cref="GrantedAuthorizationDetailsKey"/>.
    /// The RFC 9068 access-token producer reads it to embed the RFC 9396 §9.1
    /// <c>authorization_details</c> top-level claim. Transient, like the issued token strings —
    /// never persisted.
    /// </summary>
    public const string GrantedAuthorizationDetailsClaimKey = "server.grantedAuthorizationDetailsClaim";

    /// <summary>
    /// Context-bag key for the signed JARM JWT Response Document assembled by the
    /// authorize endpoint's <c>BuildInputAsync</c> for consumption by <c>BuildResponse</c>,
    /// which encodes it per the carried <c>response_mode</c> (JARM §2.3). Transient, like
    /// the issued token strings — never persisted.
    /// </summary>
    public const string JarmResponseJwtKey = "server.jarmResponseJwt";

    /// <summary>
    /// Context-bag key for the <see cref="MatchPayload"/> produced by the
    /// matched endpoint's <see cref="MatchRequestDelegate"/> during dispatch.
    /// </summary>
    /// <remarks>
    /// The dispatcher places the typed payload here after
    /// <see cref="EndpointChain.MatchAsync"/> returns; handlers that consume
    /// the payload read it through
    /// <see cref="ExchangeContextServerExtensions.MatchPayload"/> and pattern-match
    /// to the subtype they expect. Endpoints that match unconditionally on
    /// capability and method (no <see cref="ServerEndpoint.MatchesRequest"/>
    /// delegate) get <see cref="MatchPayload.Empty"/>.
    /// </remarks>
    public const string MatchPayloadKey = "server.matchPayload";

    /// <summary>
    /// Key for the active <see cref="AuthorizationServer"/> placed on the
    /// context at <see cref="AuthorizationServer.DispatchAsync"/> entry so
    /// every downstream per-request delegate can read it via
    /// <see cref="ExchangeContextServerExtensions.Server"/> rather than receiving
    /// it as a separate parameter. Phase 9h's server-on-context discipline.
    /// </summary>
    public const string ServerKey = "server.authorizationServer";

    /// <summary>
    /// Key for the per-request <see cref="EndpointChain"/> placed on the
    /// context after <see cref="EndpointChain.BuildForRequestAsync"/>
    /// completes. Read by discovery emission (which walks the chain) and by
    /// inspectors that need to know which endpoints survived the capability
    /// filter for the current registration. Phase 9h.
    /// </summary>
    public const string EndpointChainKey = "server.endpointChain";

    /// <summary>
    /// Key for the per-request set of allowed capabilities, as returned by
    /// <see cref="AuthorizationServerIntegration.ResolveCapabilitiesAsync"/>
    /// during chain build. Distinct from the endpoint chain itself — the
    /// chain reflects (capabilities ∩ endpoint-builder-emitted), while this
    /// key carries the raw resolver output. Phase 9h stored the chain; the
    /// resolved set was added during B.0.A chunk 3 for request-time
    /// capability gating that runs alongside the chain (e.g., token
    /// producer attenuation inside a token-endpoint handler).
    /// </summary>
    public const string ResolvedCapabilitiesKey = "server.resolvedCapabilities";

    /// <summary>
    /// Key for the <see cref="ConfirmationMethod"/> binding the issuance
    /// pipeline established for the current request (typically the DPoP
    /// <c>jkt</c> thumbprint per RFC 9449 §6.1). Producer code sets this
    /// before walking claim contributors so contributors that emit
    /// confirmation-related claims read it from the same per-request
    /// source as every other resolved value. Phase 9h.
    /// </summary>
    public const string ConfirmationKey = "server.confirmation";
}
