using System.Diagnostics;
using Verifiable.Cryptography.Text;

namespace Verifiable.OAuth.Oid4Vp;

/// <summary>
/// Well-known context bag key constants for OID4VP verifier request processing.
/// </summary>
/// <remarks>
/// <para>
/// The application skin places input values on the request context bag before
/// calling <see cref="EndpointServer.DispatchAsync"/>. The dispatcher and
/// endpoint delegates place output values back on the context bag so the
/// application can read them after dispatch completes.
/// </para>
/// <para>
/// The flow identifier is generated by the dispatcher at PAR time and never
/// crosses a process boundary. The application identifies a flow externally
/// only via the <c>request_uri</c> token and the URL it appears in. The
/// per-flow opaque token is placed on the context by the library before
/// <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/> is
/// invoked, so the delegate can compose URLs that incorporate the token.
/// </para>
/// </remarks>
[DebuggerDisplay("Oid4VpContextKeys")]
public static class Oid4VpContextKeys
{
    //Input keys — set by the application before dispatching.

    /// <summary>The UTF-8 source literal of <see cref="PreparedQuery"/>.</summary>
    public static ReadOnlySpan<byte> PreparedQueryUtf8 => "oid4vp.preparedQuery"u8;

    /// <summary>
    /// The prepared DCQL query describing the credentials the Verifier requires.
    /// Value type: <see cref="Verifiable.Core.Dcql.PreparedDcqlQuery"/>.
    /// </summary>
    public static readonly string PreparedQuery = Utf8Constants.ToInternedString(PreparedQueryUtf8);

    /// <summary>The UTF-8 source literal of <see cref="TransactionNonce"/>.</summary>
    public static ReadOnlySpan<byte> TransactionNonceUtf8 => "oid4vp.transactionNonce"u8;

    /// <summary>
    /// The transaction nonce bound into the JAR and echoed in the VP token.
    /// Value type: <see cref="TransactionNonce"/>.
    /// </summary>
    public static readonly string TransactionNonce = Utf8Constants.ToInternedString(TransactionNonceUtf8);

    /// <summary>The UTF-8 source literal of <see cref="DecryptionKeyId"/>.</summary>
    public static ReadOnlySpan<byte> DecryptionKeyIdUtf8 => "oid4vp.decryptionKeyId"u8;

    /// <summary>
    /// The identifier of the decryption key the Verifier will use to decrypt
    /// the Wallet's Authorization Response JWE. The corresponding public key
    /// is published in <c>client_metadata.jwks</c> inside the JAR.
    /// Value type: <see cref="Verifiable.Cryptography.KeyId"/>.
    /// </summary>
    public static readonly string DecryptionKeyId = Utf8Constants.ToInternedString(DecryptionKeyIdUtf8);

    /// <summary>The UTF-8 source literal of <see cref="RedirectUri"/>.</summary>
    public static ReadOnlySpan<byte> RedirectUriUtf8 => "oid4vp.redirectUri"u8;

    /// <summary>
    /// The <c>redirect_uri</c> returned to the Wallet in the direct_post HTTP 200
    /// response body for same-device flows per
    /// <see href="https://openid.net/specs/openid-4-verifiable-presentations-1_0.html">OID4VP 1.0 §8.2</see>.
    /// Value type: <see cref="Uri"/>, or absent for cross-device flows.
    /// Set by the application before dispatching the direct_post call.
    /// </summary>
    public static readonly string RedirectUri = Utf8Constants.ToInternedString(RedirectUriUtf8);

    /// <summary>The UTF-8 source literal of <see cref="TransactionData"/>.</summary>
    public static ReadOnlySpan<byte> TransactionDataUtf8 => "oid4vp.transactionData"u8;

    /// <summary>
    /// The <c>transaction_data</c> array bound into the JAR per
    /// <see href="https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-8.4">OID4VP 1.0 §8.4</see>.
    /// Value type: <c>IReadOnlyList&lt;string&gt;</c> — base64url-encoded JSON
    /// descriptors. Set by the application before dispatching the PAR request
    /// when transaction-data binding is required.
    /// </summary>
    public static readonly string TransactionData = Utf8Constants.ToInternedString(TransactionDataUtf8);

    /// <summary>The UTF-8 source literal of <see cref="Oid4VpResponseMode"/>.</summary>
    public static ReadOnlySpan<byte> Oid4VpResponseModeUtf8 => "oid4vp.responseMode"u8;

    /// <summary>
    /// The <c>response_mode</c> the Verifier advertises in the JAR — typically
    /// <see cref="WellKnownResponseModes.DirectPostJwt"/> (HAIP 1.0 §5.1
    /// encrypted, default) or <see cref="WellKnownResponseModes.DirectPost"/>
    /// (OID4VP 1.0 §8.2 plaintext). Set by the application before dispatching
    /// the PAR request when a non-default mode is required. Value type:
    /// <see cref="string"/>.
    /// </summary>
    public static readonly string Oid4VpResponseMode = Utf8Constants.ToInternedString(Oid4VpResponseModeUtf8);


    /// <summary>The UTF-8 source literal of <see cref="JarAdditionalHeaderClaims"/>.</summary>
    public static ReadOnlySpan<byte> JarAdditionalHeaderClaimsUtf8 => "oid4vp.jarAdditionalHeaderClaims"u8;

    /// <summary>
    /// Additional JOSE header claims to merge into the JAR's signed header
    /// when the JAR is built. Used to inject prefix-specific material —
    /// the <c>trust_chain</c> array for the <c>openid_federation:</c>
    /// client_id prefix, the <c>x5c</c> array for <c>x509_san_dns:</c>, the
    /// <c>jwt</c> attestation for <c>verifier_attestation:</c>. Value type:
    /// <see cref="Verifiable.JCose.JwtHeader"/>. Set by the application
    /// before dispatching the PAR request.
    /// </summary>
    /// <remarks>
    /// The standard <c>alg</c> and <c>typ</c> header entries are not
    /// overridable; any entries with those keys are ignored by
    /// <see cref="JarExtensions"/>. Per OID4VP 1.0 §5.9.3 the appropriate
    /// header set depends on the client_id prefix the deployment uses.
    /// </remarks>
    public static readonly string JarAdditionalHeaderClaims = Utf8Constants.ToInternedString(JarAdditionalHeaderClaimsUtf8);


    //Library-internal keys — placed on the context by library code before
    //invoking application delegates, so the delegates have the per-flow
    //inputs they need to compose URLs.

    /// <summary>The UTF-8 source literal of <see cref="ParHandle"/>.</summary>
    public static ReadOnlySpan<byte> ParHandleUtf8 => "oid4vp.parHandle"u8;

    /// <summary>
    /// The opaque per-flow token that the application's
    /// <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/>
    /// delegate reads when composing the <c>request_uri</c> URL with key
    /// <see cref="Oid4VpEndpointKeys.RequestUri"/>.
    /// Value type: <see cref="string"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Placed on the context by the library's PAR endpoint immediately before
    /// it invokes <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/>.
    /// The token is unrelated to the internal flow identifier; the flow
    /// identifier never leaves the server process. The delegate composes the
    /// URL using the deployment's routing scheme, incorporating the token
    /// however the deployment encodes per-flow handles (path segment, query
    /// parameter, header, etc.).
    /// </para>
    /// <para>
    /// The same token value becomes the JAR's <c>state</c> claim and the
    /// form field the Wallet echoes in the direct_post per OID4VP 1.0 §6.1
    /// and RFC 6749 §4.1.1, so that
    /// <see cref="AuthorizationServerIntegration.ResolveCorrelationKeyAsync"/>
    /// can map the inbound handle back to the internal flow identifier.
    /// </para>
    /// </remarks>
    public static readonly string ParHandle = Utf8Constants.ToInternedString(ParHandleUtf8);


    //Output keys — set by the endpoint delegates, read by the application
    //after dispatch.

    /// <summary>The UTF-8 source literal of <see cref="GeneratedRequestUri"/>.</summary>
    public static ReadOnlySpan<byte> GeneratedRequestUriUtf8 => "oid4vp.generatedRequestUri"u8;

    /// <summary>
    /// The full <c>request_uri</c> generated by the PAR endpoint. The application
    /// reads this after PAR dispatch returns to encode the URL into a QR code
    /// or deep link.
    /// Value type: <see cref="Uri"/>.
    /// </summary>
    public static readonly string GeneratedRequestUri = Utf8Constants.ToInternedString(GeneratedRequestUriUtf8);

    /// <summary>The UTF-8 source literal of <see cref="CompactJar"/>.</summary>
    public static ReadOnlySpan<byte> CompactJarUtf8 => "oid4vp.compactJar"u8;

    /// <summary>
    /// The compact JWS JAR produced by the JAR request endpoint. The application
    /// reads this after the JAR-fetch dispatch returns to write the body of the
    /// HTTP response.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public static readonly string CompactJar = Utf8Constants.ToInternedString(CompactJarUtf8);
}
