using System.Diagnostics;

namespace Verifiable.OAuth.Oid4Vp;

/// <summary>
/// Well-known context bag key constants for OID4VP verifier request processing.
/// </summary>
/// <remarks>
/// <para>
/// The application skin places input values on the request context bag before
/// calling <see cref="AuthorizationServer.DispatchAsync"/>. The dispatcher and
/// endpoint delegates place output values back on the context bag so the
/// application can read them after dispatch completes.
/// </para>
/// <para>
/// The flow identifier is generated by the dispatcher at PAR time and never
/// crosses a process boundary. The application identifies a flow externally
/// only via the <c>request_uri</c> token and the URL it appears in. The
/// per-flow opaque token is placed on the context by the library before
/// <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/> is
/// invoked, so the delegate can compose URLs that incorporate the token.
/// </para>
/// </remarks>
[DebuggerDisplay("Oid4VpContextKeys")]
public static class Oid4VpContextKeys
{
    //Input keys — set by the application before dispatching.

    /// <summary>
    /// The prepared DCQL query describing the credentials the Verifier requires.
    /// Value type: <see cref="Verifiable.Core.Dcql.PreparedDcqlQuery"/>.
    /// </summary>
    public static readonly string PreparedQuery = "oid4vp.preparedQuery";

    /// <summary>
    /// The transaction nonce bound into the JAR and echoed in the VP token.
    /// Value type: <see cref="TransactionNonce"/>.
    /// </summary>
    public static readonly string TransactionNonce = "oid4vp.transactionNonce";

    /// <summary>
    /// The identifier of the decryption key the Verifier will use to decrypt
    /// the Wallet's Authorization Response JWE. The corresponding public key
    /// is published in <c>client_metadata.jwks</c> inside the JAR.
    /// Value type: <see cref="Verifiable.Cryptography.KeyId"/>.
    /// </summary>
    public static readonly string DecryptionKeyId = "oid4vp.decryptionKeyId";

    /// <summary>
    /// The <c>redirect_uri</c> returned to the Wallet in the direct_post HTTP 200
    /// response body for same-device flows per
    /// <see href="https://openid.net/specs/openid-4-verifiable-presentations-1_0.html">OID4VP 1.0 §8.2</see>.
    /// Value type: <see cref="Uri"/>, or absent for cross-device flows.
    /// Set by the application before dispatching the direct_post call.
    /// </summary>
    public static readonly string RedirectUri = "oid4vp.redirectUri";


    //Library-internal keys — placed on the context by library code before
    //invoking application delegates, so the delegates have the per-flow
    //inputs they need to compose URLs.

    /// <summary>
    /// The opaque per-flow token that the application's
    /// <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/>
    /// delegate reads when composing the <c>request_uri</c> URL with key
    /// <see cref="Oid4VpEndpointKeys.RequestUri"/>.
    /// Value type: <see cref="string"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Placed on the context by the library's PAR endpoint immediately before
    /// it invokes <see cref="AuthorizationServerIntegration.ResolveEndpointUriAsync"/>.
    /// The token is unrelated to the internal flow identifier; the flow
    /// identifier never leaves the server process. The delegate composes the
    /// URL using the deployment's routing scheme, incorporating the token
    /// however the deployment encodes per-flow handles (path segment, query
    /// parameter, header, etc.).
    /// </para>
    /// <para>
    /// The same token value becomes the JAR's <c>state</c> claim and the
    /// form field the Wallet echoes in the direct_post per OID4VP 1.0 §6.1
    /// and RFC 6749 §4.1.1, so that
    /// <see cref="AuthorizationServerIntegration.ResolveCorrelationKeyAsync"/>
    /// can map the inbound handle back to the internal flow identifier.
    /// </para>
    /// </remarks>
    public static readonly string ParHandle = "oid4vp.parHandle";


    //Output keys — set by the endpoint delegates, read by the application
    //after dispatch.

    /// <summary>
    /// The full <c>request_uri</c> generated by the PAR endpoint. The application
    /// reads this after PAR dispatch returns to encode the URL into a QR code
    /// or deep link.
    /// Value type: <see cref="Uri"/>.
    /// </summary>
    public static readonly string GeneratedRequestUri = "oid4vp.generatedRequestUri";

    /// <summary>
    /// The compact JWS JAR produced by the JAR request endpoint. The application
    /// reads this after the JAR-fetch dispatch returns to write the body of the
    /// HTTP response.
    /// Value type: <see cref="string"/>.
    /// </summary>
    public static readonly string CompactJar = "oid4vp.compactJar";
}
