using System.Diagnostics;
using Verifiable.Core.Dcql;
using Verifiable.Cryptography;

namespace Verifiable.OAuth.Oid4Vp;

/// <summary>
/// Carries a successful PAR HTTP response. Transitions from <see cref="ParRequestReady"/>
/// to <see cref="ParCompleted"/>. This input arrives at the first DB persistence point.
/// </summary>
/// <param name="Par">The PAR response body parsed from the authorization server.</param>
/// <param name="Nonce">The freshly generated transaction nonce for this flow.</param>
/// <param name="Query">The prepared DCQL query to embed in the JAR.</param>
/// <param name="DecryptionKeyId">
/// The identifier of the ephemeral private key that will decrypt the
/// <c>direct_post.jwt</c> authorization response. The key was generated by the caller,
/// its public component embedded in the JAR, and the private scalar stored under this
/// identifier before this input was raised. The identifier is opaque to the library —
/// it may be a UUID in a local secret store, a KMS key ARN, or a DID key identifier.
/// The application's key resolver uses it to load the live key material when decryption
/// is needed.
/// </param>
/// <param name="ReceivedAt">The UTC instant the PAR response was received.</param>
[DebuggerDisplay("ParSucceeded RequestUri={Par.RequestUri}")]
public sealed record ParSucceeded(
    ParResponse Par,
    TransactionNonce Nonce,
    PreparedDcqlQuery Query,
    KeyId DecryptionKeyId,
    DateTimeOffset ReceivedAt): OAuthFlowInput;
